/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n camera_fifo -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5a00 -type ebfifo -depth 2 -width 256 -depth 2 -rdata_width 256 -no_enable -pe -1 -pf -1  */
/* Thu Jan 20 17:50:37 2022 */


`timescale 1 ns / 1 ps
module camera_fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [255:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [255:0] Q;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire w_gdata_0;
    wire wptr_0;
    wire wptr_1;
    wire r_gdata_0;
    wire rptr_0;
    wire rptr_1;
    wire w_gcount_0;
    wire w_gcount_1;
    wire r_gcount_0;
    wire r_gcount_1;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire empty_i;
    wire rRst;
    wire full_i;
    wire iwcount_0;
    wire iwcount_1;
    wire co0;
    wire w_gctr_ci;
    wire wcount_1;
    wire scuba_vhi;
    wire ircount_0;
    wire ircount_1;
    wire co0_1;
    wire r_gctr_ci;
    wire rcount_1;
    wire rden_i;
    wire cmp_ci;
    wire wcount_r0;
    wire empty_cmp_clr;
    wire rcount_0;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire wren_i;
    wire cmp_ci_1;
    wire rcount_w0;
    wire full_cmp_clr;
    wire wcount_0;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire scuba_vlo;

    AND2 AND2_t4 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t3 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t2 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t1 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t0 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    // synopsys translate_off
    defparam LUT4_5.initval =  16'h6996 ;
    // synopsys translate_on
    ROM16X1 LUT4_5 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r0))
             /* synthesis initval="0x6996" */;

    // synopsys translate_off
    defparam LUT4_4.initval =  16'h6996 ;
    // synopsys translate_on
    ROM16X1 LUT4_4 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w0))
             /* synthesis initval="0x6996" */;

    // synopsys translate_off
    defparam LUT4_3.initval =  16'h0410 ;
    // synopsys translate_on
    ROM16X1 LUT4_3 (.AD3(rptr_1), .AD2(rcount_1), .AD1(w_gcount_r21), .AD0(scuba_vlo), 
        .DO0(empty_cmp_set))
             /* synthesis initval="0x0410" */;

    // synopsys translate_off
    defparam LUT4_2.initval =  16'h1004 ;
    // synopsys translate_on
    ROM16X1 LUT4_2 (.AD3(rptr_1), .AD2(rcount_1), .AD1(w_gcount_r21), .AD0(scuba_vlo), 
        .DO0(empty_cmp_clr))
             /* synthesis initval="0x1004" */;

    // synopsys translate_off
    defparam LUT4_1.initval =  16'h0140 ;
    // synopsys translate_on
    ROM16X1 LUT4_1 (.AD3(wptr_1), .AD2(wcount_1), .AD1(r_gcount_w21), .AD0(scuba_vlo), 
        .DO0(full_cmp_set))
             /* synthesis initval="0x0140" */;

    // synopsys translate_off
    defparam LUT4_0.initval =  16'h4001 ;
    // synopsys translate_on
    ROM16X1 LUT4_0 (.AD3(wptr_1), .AD2(wcount_1), .AD1(r_gcount_w21), .AD0(scuba_vlo), 
        .DO0(full_cmp_clr))
             /* synthesis initval="0x4001" */;

    // synopsys translate_off
    defparam pdp_ram_0_0_7.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_0_7.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_0_7.GSR = "DISABLED" ;
    defparam pdp_ram_0_0_7.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_7.REGMODE = "NOREG" ;
    defparam pdp_ram_0_0_7.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_0_7.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_0_7 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), 
        .DI8(Data[8]), .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), 
        .DI12(Data[12]), .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), 
        .DI16(Data[16]), .DI17(Data[17]), .DI18(Data[18]), .DI19(Data[19]), 
        .DI20(Data[20]), .DI21(Data[21]), .DI22(Data[22]), .DI23(Data[23]), 
        .DI24(Data[24]), .DI25(Data[25]), .DI26(Data[26]), .DI27(Data[27]), 
        .DI28(Data[28]), .DI29(Data[29]), .DI30(Data[30]), .DI31(Data[31]), 
        .DI32(Data[32]), .DI33(Data[33]), .DI34(Data[34]), .DI35(Data[35]), 
        .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), .ADW3(scuba_vlo), 
        .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), .ADW7(scuba_vlo), 
        .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), .BE2(scuba_vhi), 
        .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), .CSW0(scuba_vhi), 
        .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), .ADR1(scuba_vlo), 
        .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), .ADR5(rptr_0), 
        .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), .ADR9(scuba_vlo), 
        .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), .ADR13(scuba_vlo), 
        .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), .CSR1(scuba_vlo), 
        .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[18]), .DO1(Q[19]), .DO2(Q[20]), 
        .DO3(Q[21]), .DO4(Q[22]), .DO5(Q[23]), .DO6(Q[24]), .DO7(Q[25]), 
        .DO8(Q[26]), .DO9(Q[27]), .DO10(Q[28]), .DO11(Q[29]), .DO12(Q[30]), 
        .DO13(Q[31]), .DO14(Q[32]), .DO15(Q[33]), .DO16(Q[34]), .DO17(Q[35]), 
        .DO18(Q[0]), .DO19(Q[1]), .DO20(Q[2]), .DO21(Q[3]), .DO22(Q[4]), 
        .DO23(Q[5]), .DO24(Q[6]), .DO25(Q[7]), .DO26(Q[8]), .DO27(Q[9]), 
        .DO28(Q[10]), .DO29(Q[11]), .DO30(Q[12]), .DO31(Q[13]), .DO32(Q[14]), 
        .DO33(Q[15]), .DO34(Q[16]), .DO35(Q[17]))
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam pdp_ram_0_1_6.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_1_6.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_1_6.GSR = "DISABLED" ;
    defparam pdp_ram_0_1_6.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_1_6.REGMODE = "NOREG" ;
    defparam pdp_ram_0_1_6.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_1_6.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_1_6 (.DI0(Data[36]), .DI1(Data[37]), .DI2(Data[38]), 
        .DI3(Data[39]), .DI4(Data[40]), .DI5(Data[41]), .DI6(Data[42]), 
        .DI7(Data[43]), .DI8(Data[44]), .DI9(Data[45]), .DI10(Data[46]), 
        .DI11(Data[47]), .DI12(Data[48]), .DI13(Data[49]), .DI14(Data[50]), 
        .DI15(Data[51]), .DI16(Data[52]), .DI17(Data[53]), .DI18(Data[54]), 
        .DI19(Data[55]), .DI20(Data[56]), .DI21(Data[57]), .DI22(Data[58]), 
        .DI23(Data[59]), .DI24(Data[60]), .DI25(Data[61]), .DI26(Data[62]), 
        .DI27(Data[63]), .DI28(Data[64]), .DI29(Data[65]), .DI30(Data[66]), 
        .DI31(Data[67]), .DI32(Data[68]), .DI33(Data[69]), .DI34(Data[70]), 
        .DI35(Data[71]), .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW0(scuba_vhi), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(rptr_0), .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[54]), .DO1(Q[55]), 
        .DO2(Q[56]), .DO3(Q[57]), .DO4(Q[58]), .DO5(Q[59]), .DO6(Q[60]), 
        .DO7(Q[61]), .DO8(Q[62]), .DO9(Q[63]), .DO10(Q[64]), .DO11(Q[65]), 
        .DO12(Q[66]), .DO13(Q[67]), .DO14(Q[68]), .DO15(Q[69]), .DO16(Q[70]), 
        .DO17(Q[71]), .DO18(Q[36]), .DO19(Q[37]), .DO20(Q[38]), .DO21(Q[39]), 
        .DO22(Q[40]), .DO23(Q[41]), .DO24(Q[42]), .DO25(Q[43]), .DO26(Q[44]), 
        .DO27(Q[45]), .DO28(Q[46]), .DO29(Q[47]), .DO30(Q[48]), .DO31(Q[49]), 
        .DO32(Q[50]), .DO33(Q[51]), .DO34(Q[52]), .DO35(Q[53]))
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam pdp_ram_0_2_5.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_2_5.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_2_5.GSR = "DISABLED" ;
    defparam pdp_ram_0_2_5.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_2_5.REGMODE = "NOREG" ;
    defparam pdp_ram_0_2_5.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_2_5.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_2_5 (.DI0(Data[72]), .DI1(Data[73]), .DI2(Data[74]), 
        .DI3(Data[75]), .DI4(Data[76]), .DI5(Data[77]), .DI6(Data[78]), 
        .DI7(Data[79]), .DI8(Data[80]), .DI9(Data[81]), .DI10(Data[82]), 
        .DI11(Data[83]), .DI12(Data[84]), .DI13(Data[85]), .DI14(Data[86]), 
        .DI15(Data[87]), .DI16(Data[88]), .DI17(Data[89]), .DI18(Data[90]), 
        .DI19(Data[91]), .DI20(Data[92]), .DI21(Data[93]), .DI22(Data[94]), 
        .DI23(Data[95]), .DI24(Data[96]), .DI25(Data[97]), .DI26(Data[98]), 
        .DI27(Data[99]), .DI28(Data[100]), .DI29(Data[101]), .DI30(Data[102]), 
        .DI31(Data[103]), .DI32(Data[104]), .DI33(Data[105]), .DI34(Data[106]), 
        .DI35(Data[107]), .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW0(scuba_vhi), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(rptr_0), .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[90]), .DO1(Q[91]), 
        .DO2(Q[92]), .DO3(Q[93]), .DO4(Q[94]), .DO5(Q[95]), .DO6(Q[96]), 
        .DO7(Q[97]), .DO8(Q[98]), .DO9(Q[99]), .DO10(Q[100]), .DO11(Q[101]), 
        .DO12(Q[102]), .DO13(Q[103]), .DO14(Q[104]), .DO15(Q[105]), .DO16(Q[106]), 
        .DO17(Q[107]), .DO18(Q[72]), .DO19(Q[73]), .DO20(Q[74]), .DO21(Q[75]), 
        .DO22(Q[76]), .DO23(Q[77]), .DO24(Q[78]), .DO25(Q[79]), .DO26(Q[80]), 
        .DO27(Q[81]), .DO28(Q[82]), .DO29(Q[83]), .DO30(Q[84]), .DO31(Q[85]), 
        .DO32(Q[86]), .DO33(Q[87]), .DO34(Q[88]), .DO35(Q[89]))
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam pdp_ram_0_3_4.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_3_4.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_3_4.GSR = "DISABLED" ;
    defparam pdp_ram_0_3_4.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_3_4.REGMODE = "NOREG" ;
    defparam pdp_ram_0_3_4.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_3_4.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_3_4 (.DI0(Data[108]), .DI1(Data[109]), .DI2(Data[110]), 
        .DI3(Data[111]), .DI4(Data[112]), .DI5(Data[113]), .DI6(Data[114]), 
        .DI7(Data[115]), .DI8(Data[116]), .DI9(Data[117]), .DI10(Data[118]), 
        .DI11(Data[119]), .DI12(Data[120]), .DI13(Data[121]), .DI14(Data[122]), 
        .DI15(Data[123]), .DI16(Data[124]), .DI17(Data[125]), .DI18(Data[126]), 
        .DI19(Data[127]), .DI20(Data[128]), .DI21(Data[129]), .DI22(Data[130]), 
        .DI23(Data[131]), .DI24(Data[132]), .DI25(Data[133]), .DI26(Data[134]), 
        .DI27(Data[135]), .DI28(Data[136]), .DI29(Data[137]), .DI30(Data[138]), 
        .DI31(Data[139]), .DI32(Data[140]), .DI33(Data[141]), .DI34(Data[142]), 
        .DI35(Data[143]), .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW0(scuba_vhi), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(rptr_0), .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[126]), .DO1(Q[127]), 
        .DO2(Q[128]), .DO3(Q[129]), .DO4(Q[130]), .DO5(Q[131]), .DO6(Q[132]), 
        .DO7(Q[133]), .DO8(Q[134]), .DO9(Q[135]), .DO10(Q[136]), .DO11(Q[137]), 
        .DO12(Q[138]), .DO13(Q[139]), .DO14(Q[140]), .DO15(Q[141]), .DO16(Q[142]), 
        .DO17(Q[143]), .DO18(Q[108]), .DO19(Q[109]), .DO20(Q[110]), .DO21(Q[111]), 
        .DO22(Q[112]), .DO23(Q[113]), .DO24(Q[114]), .DO25(Q[115]), .DO26(Q[116]), 
        .DO27(Q[117]), .DO28(Q[118]), .DO29(Q[119]), .DO30(Q[120]), .DO31(Q[121]), 
        .DO32(Q[122]), .DO33(Q[123]), .DO34(Q[124]), .DO35(Q[125]))
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam pdp_ram_0_4_3.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_4_3.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_4_3.GSR = "DISABLED" ;
    defparam pdp_ram_0_4_3.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_4_3.REGMODE = "NOREG" ;
    defparam pdp_ram_0_4_3.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_4_3.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_4_3 (.DI0(Data[144]), .DI1(Data[145]), .DI2(Data[146]), 
        .DI3(Data[147]), .DI4(Data[148]), .DI5(Data[149]), .DI6(Data[150]), 
        .DI7(Data[151]), .DI8(Data[152]), .DI9(Data[153]), .DI10(Data[154]), 
        .DI11(Data[155]), .DI12(Data[156]), .DI13(Data[157]), .DI14(Data[158]), 
        .DI15(Data[159]), .DI16(Data[160]), .DI17(Data[161]), .DI18(Data[162]), 
        .DI19(Data[163]), .DI20(Data[164]), .DI21(Data[165]), .DI22(Data[166]), 
        .DI23(Data[167]), .DI24(Data[168]), .DI25(Data[169]), .DI26(Data[170]), 
        .DI27(Data[171]), .DI28(Data[172]), .DI29(Data[173]), .DI30(Data[174]), 
        .DI31(Data[175]), .DI32(Data[176]), .DI33(Data[177]), .DI34(Data[178]), 
        .DI35(Data[179]), .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW0(scuba_vhi), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(rptr_0), .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[162]), .DO1(Q[163]), 
        .DO2(Q[164]), .DO3(Q[165]), .DO4(Q[166]), .DO5(Q[167]), .DO6(Q[168]), 
        .DO7(Q[169]), .DO8(Q[170]), .DO9(Q[171]), .DO10(Q[172]), .DO11(Q[173]), 
        .DO12(Q[174]), .DO13(Q[175]), .DO14(Q[176]), .DO15(Q[177]), .DO16(Q[178]), 
        .DO17(Q[179]), .DO18(Q[144]), .DO19(Q[145]), .DO20(Q[146]), .DO21(Q[147]), 
        .DO22(Q[148]), .DO23(Q[149]), .DO24(Q[150]), .DO25(Q[151]), .DO26(Q[152]), 
        .DO27(Q[153]), .DO28(Q[154]), .DO29(Q[155]), .DO30(Q[156]), .DO31(Q[157]), 
        .DO32(Q[158]), .DO33(Q[159]), .DO34(Q[160]), .DO35(Q[161]))
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam pdp_ram_0_5_2.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_5_2.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_5_2.GSR = "DISABLED" ;
    defparam pdp_ram_0_5_2.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_5_2.REGMODE = "NOREG" ;
    defparam pdp_ram_0_5_2.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_5_2.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_5_2 (.DI0(Data[180]), .DI1(Data[181]), .DI2(Data[182]), 
        .DI3(Data[183]), .DI4(Data[184]), .DI5(Data[185]), .DI6(Data[186]), 
        .DI7(Data[187]), .DI8(Data[188]), .DI9(Data[189]), .DI10(Data[190]), 
        .DI11(Data[191]), .DI12(Data[192]), .DI13(Data[193]), .DI14(Data[194]), 
        .DI15(Data[195]), .DI16(Data[196]), .DI17(Data[197]), .DI18(Data[198]), 
        .DI19(Data[199]), .DI20(Data[200]), .DI21(Data[201]), .DI22(Data[202]), 
        .DI23(Data[203]), .DI24(Data[204]), .DI25(Data[205]), .DI26(Data[206]), 
        .DI27(Data[207]), .DI28(Data[208]), .DI29(Data[209]), .DI30(Data[210]), 
        .DI31(Data[211]), .DI32(Data[212]), .DI33(Data[213]), .DI34(Data[214]), 
        .DI35(Data[215]), .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW0(scuba_vhi), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(rptr_0), .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[198]), .DO1(Q[199]), 
        .DO2(Q[200]), .DO3(Q[201]), .DO4(Q[202]), .DO5(Q[203]), .DO6(Q[204]), 
        .DO7(Q[205]), .DO8(Q[206]), .DO9(Q[207]), .DO10(Q[208]), .DO11(Q[209]), 
        .DO12(Q[210]), .DO13(Q[211]), .DO14(Q[212]), .DO15(Q[213]), .DO16(Q[214]), 
        .DO17(Q[215]), .DO18(Q[180]), .DO19(Q[181]), .DO20(Q[182]), .DO21(Q[183]), 
        .DO22(Q[184]), .DO23(Q[185]), .DO24(Q[186]), .DO25(Q[187]), .DO26(Q[188]), 
        .DO27(Q[189]), .DO28(Q[190]), .DO29(Q[191]), .DO30(Q[192]), .DO31(Q[193]), 
        .DO32(Q[194]), .DO33(Q[195]), .DO34(Q[196]), .DO35(Q[197]))
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam pdp_ram_0_6_1.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_6_1.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_6_1.GSR = "DISABLED" ;
    defparam pdp_ram_0_6_1.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_6_1.REGMODE = "NOREG" ;
    defparam pdp_ram_0_6_1.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_6_1.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_6_1 (.DI0(Data[216]), .DI1(Data[217]), .DI2(Data[218]), 
        .DI3(Data[219]), .DI4(Data[220]), .DI5(Data[221]), .DI6(Data[222]), 
        .DI7(Data[223]), .DI8(Data[224]), .DI9(Data[225]), .DI10(Data[226]), 
        .DI11(Data[227]), .DI12(Data[228]), .DI13(Data[229]), .DI14(Data[230]), 
        .DI15(Data[231]), .DI16(Data[232]), .DI17(Data[233]), .DI18(Data[234]), 
        .DI19(Data[235]), .DI20(Data[236]), .DI21(Data[237]), .DI22(Data[238]), 
        .DI23(Data[239]), .DI24(Data[240]), .DI25(Data[241]), .DI26(Data[242]), 
        .DI27(Data[243]), .DI28(Data[244]), .DI29(Data[245]), .DI30(Data[246]), 
        .DI31(Data[247]), .DI32(Data[248]), .DI33(Data[249]), .DI34(Data[250]), 
        .DI35(Data[251]), .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW0(scuba_vhi), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(rptr_0), .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[234]), .DO1(Q[235]), 
        .DO2(Q[236]), .DO3(Q[237]), .DO4(Q[238]), .DO5(Q[239]), .DO6(Q[240]), 
        .DO7(Q[241]), .DO8(Q[242]), .DO9(Q[243]), .DO10(Q[244]), .DO11(Q[245]), 
        .DO12(Q[246]), .DO13(Q[247]), .DO14(Q[248]), .DO15(Q[249]), .DO16(Q[250]), 
        .DO17(Q[251]), .DO18(Q[216]), .DO19(Q[217]), .DO20(Q[218]), .DO21(Q[219]), 
        .DO22(Q[220]), .DO23(Q[221]), .DO24(Q[222]), .DO25(Q[223]), .DO26(Q[224]), 
        .DO27(Q[225]), .DO28(Q[226]), .DO29(Q[227]), .DO30(Q[228]), .DO31(Q[229]), 
        .DO32(Q[230]), .DO33(Q[231]), .DO34(Q[232]), .DO35(Q[233]))
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam pdp_ram_0_7_0.CSDECODE_R =  3'b000 ;
    defparam pdp_ram_0_7_0.CSDECODE_W =  3'b001 ;
    defparam pdp_ram_0_7_0.GSR = "DISABLED" ;
    defparam pdp_ram_0_7_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_7_0.REGMODE = "NOREG" ;
    defparam pdp_ram_0_7_0.DATA_WIDTH_R = 36 ;
    defparam pdp_ram_0_7_0.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB pdp_ram_0_7_0 (.DI0(Data[252]), .DI1(Data[253]), .DI2(Data[254]), 
        .DI3(Data[255]), .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(scuba_vlo), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .DI18(scuba_vlo), 
        .DI19(scuba_vlo), .DI20(scuba_vlo), .DI21(scuba_vlo), .DI22(scuba_vlo), 
        .DI23(scuba_vlo), .DI24(scuba_vlo), .DI25(scuba_vlo), .DI26(scuba_vlo), 
        .DI27(scuba_vlo), .DI28(scuba_vlo), .DI29(scuba_vlo), .DI30(scuba_vlo), 
        .DI31(scuba_vlo), .DI32(scuba_vlo), .DI33(scuba_vlo), .DI34(scuba_vlo), 
        .DI35(scuba_vlo), .ADW0(wptr_0), .ADW1(scuba_vlo), .ADW2(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW4(scuba_vlo), .ADW5(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW0(scuba_vhi), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(rptr_0), .ADR6(scuba_vlo), .ADR7(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR9(scuba_vlo), .ADR10(scuba_vlo), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(rden_i), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(), .DO1(), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(Q[252]), .DO19(Q[253]), .DO20(Q[254]), .DO21(Q[255]), .DO22(), 
        .DO23(), .DO24(), .DO25(), .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), 
        .DO31(), .DO32(), .DO33(), .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="camera_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam FF_21.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3BX FF_21 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_20.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_20 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_19.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_19 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_18.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_18 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_17.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_17 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_16.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_16 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3BX FF_15 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_9 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_8 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_7 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_6 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_5 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_4 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_3 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_2 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3BX FF_1 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_0 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FADD2B w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(w_gctr_ci), .S0(), .S1());

    CU2 w_gctr_0 (.CI(w_gctr_ci), .PC0(wcount_0), .PC1(wcount_1), .CO(co0), 
        .NC0(iwcount_0), .NC1(iwcount_1));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(r_gctr_ci), .S0(), .S1());

    CU2 r_gctr_0 (.CI(r_gctr_ci), .PC0(rcount_0), .PC1(rcount_1), .CO(co0_1), 
        .NC0(ircount_0), .NC1(ircount_1));

    FADD2B empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());

    AGEB2 empty_cmp_0 (.A0(rcount_0), .A1(empty_cmp_set), .B0(wcount_r0), 
        .B1(empty_cmp_clr), .CI(cmp_ci), .GE(empty_d_c));

    FADD2B a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(empty_d_c), .COUT(), .S0(empty_d), .S1());

    FADD2B full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .CI(scuba_vlo), .COUT(cmp_ci_1), .S0(), .S1());

    AGEB2 full_cmp_0 (.A0(wcount_0), .A1(full_cmp_set), .B0(rcount_w0), 
        .B1(full_cmp_clr), .CI(cmp_ci_1), .GE(full_d_c));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(full_d_c), .COUT(), .S0(full_d), .S1());

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute LUT4_5 initval 0x6996
    // exemplar attribute LUT4_4 initval 0x6996
    // exemplar attribute LUT4_3 initval 0x0410
    // exemplar attribute LUT4_2 initval 0x1004
    // exemplar attribute LUT4_1 initval 0x0140
    // exemplar attribute LUT4_0 initval 0x4001
    // exemplar attribute pdp_ram_0_0_7 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_0_7 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_0_7 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_0_7 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_0_7 GSR DISABLED
    // exemplar attribute pdp_ram_0_0_7 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_0_7 REGMODE NOREG
    // exemplar attribute pdp_ram_0_0_7 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_0_7 DATA_WIDTH_W 36
    // exemplar attribute pdp_ram_0_1_6 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_1_6 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_6 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_1_6 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_1_6 GSR DISABLED
    // exemplar attribute pdp_ram_0_1_6 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_1_6 REGMODE NOREG
    // exemplar attribute pdp_ram_0_1_6 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_1_6 DATA_WIDTH_W 36
    // exemplar attribute pdp_ram_0_2_5 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_2_5 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_2_5 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_2_5 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_2_5 GSR DISABLED
    // exemplar attribute pdp_ram_0_2_5 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_2_5 REGMODE NOREG
    // exemplar attribute pdp_ram_0_2_5 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_2_5 DATA_WIDTH_W 36
    // exemplar attribute pdp_ram_0_3_4 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_3_4 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_3_4 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_3_4 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_3_4 GSR DISABLED
    // exemplar attribute pdp_ram_0_3_4 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_3_4 REGMODE NOREG
    // exemplar attribute pdp_ram_0_3_4 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_3_4 DATA_WIDTH_W 36
    // exemplar attribute pdp_ram_0_4_3 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_4_3 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_4_3 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_4_3 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_4_3 GSR DISABLED
    // exemplar attribute pdp_ram_0_4_3 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_4_3 REGMODE NOREG
    // exemplar attribute pdp_ram_0_4_3 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_4_3 DATA_WIDTH_W 36
    // exemplar attribute pdp_ram_0_5_2 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_5_2 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_5_2 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_5_2 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_5_2 GSR DISABLED
    // exemplar attribute pdp_ram_0_5_2 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_5_2 REGMODE NOREG
    // exemplar attribute pdp_ram_0_5_2 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_5_2 DATA_WIDTH_W 36
    // exemplar attribute pdp_ram_0_6_1 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_6_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_6_1 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_6_1 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_6_1 GSR DISABLED
    // exemplar attribute pdp_ram_0_6_1 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_6_1 REGMODE NOREG
    // exemplar attribute pdp_ram_0_6_1 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_6_1 DATA_WIDTH_W 36
    // exemplar attribute pdp_ram_0_7_0 MEM_LPC_FILE camera_fifo.lpc
    // exemplar attribute pdp_ram_0_7_0 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_7_0 CSDECODE_R 0b000
    // exemplar attribute pdp_ram_0_7_0 CSDECODE_W 0b001
    // exemplar attribute pdp_ram_0_7_0 GSR DISABLED
    // exemplar attribute pdp_ram_0_7_0 RESETMODE ASYNC
    // exemplar attribute pdp_ram_0_7_0 REGMODE NOREG
    // exemplar attribute pdp_ram_0_7_0 DATA_WIDTH_R 36
    // exemplar attribute pdp_ram_0_7_0 DATA_WIDTH_W 36
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
