/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 2.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n g_green -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5a00 -type rom -addr_width 6 -num_rows 64 -data_width 16 -outdata REGISTERED -memfile c:/users/μάρκος/desktop/διπλωματική/matlab/g_green_lut.mem -memformat bin  */
/* Wed Jan 12 17:31:23 2022 */


`timescale 1 ns / 1 ps
module g_green (Address, OutClock, OutClockEn, Reset, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [5:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [15:0] Q;

    wire qdataout15_ffin;
    wire qdataout14_ffin;
    wire qdataout13_ffin;
    wire qdataout12_ffin;
    wire qdataout11_ffin;
    wire qdataout10_ffin;
    wire qdataout9_ffin;
    wire qdataout8_ffin;
    wire qdataout7_ffin;
    wire qdataout6_ffin;
    wire qdataout5_ffin;
    wire qdataout4_ffin;
    wire qdataout3_ffin;
    wire qdataout2_ffin;
    wire qdataout1_ffin;
    wire qdataout0_ffin;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_15 (.D(qdataout15_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(qdataout14_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(qdataout13_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(qdataout12_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(qdataout11_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(qdataout10_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_9 (.D(qdataout9_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_8 (.D(qdataout8_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_7 (.D(qdataout7_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(qdataout6_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(qdataout5_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_15.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_15 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout15_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_14.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_14 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout14_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_13.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_13 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout13_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_12.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_12 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout12_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_11.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_11 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout11_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_10.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_10 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout10_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_9.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_9 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout9_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_8.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_8 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout8_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_7.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_7 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout7_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_6.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    ROM64X1 mem_0_6 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout6_ffin))
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_5.initval =  64'hFFFFFFFFFFFC0000 ;
    // synopsys translate_on
    ROM64X1 mem_0_5 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout5_ffin))
             /* synthesis initval="0xFFFFFFFFFFFC0000" */;

    // synopsys translate_off
    defparam mem_0_4.initval =  64'hFFFFFFF00003FFE0 ;
    // synopsys translate_on
    ROM64X1 mem_0_4 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout4_ffin))
             /* synthesis initval="0xFFFFFFF00003FFE0" */;

    // synopsys translate_off
    defparam mem_0_3.initval =  64'hFFFF800FF803FC18 ;
    // synopsys translate_on
    ROM64X1 mem_0_3 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout3_ffin))
             /* synthesis initval="0xFFFF800FF803FC18" */;

    // synopsys translate_off
    defparam mem_0_2.initval =  64'hFFE07F0F87C3C396 ;
    // synopsys translate_on
    ROM64X1 mem_0_2 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout2_ffin))
             /* synthesis initval="0xFFE07F0F87C3C396" */;

    // synopsys translate_off
    defparam mem_0_1.initval =  64'hFE1C78CC6733324C ;
    // synopsys translate_on
    ROM64X1 mem_0_1 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout1_ffin))
             /* synthesis initval="0xFE1C78CC6733324C" */;

    // synopsys translate_off
    defparam mem_0_0.initval =  64'hF19B64AB56AAAB14 ;
    // synopsys translate_on
    ROM64X1 mem_0_0 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout0_ffin))
             /* synthesis initval="0xF19B64AB56AAAB14" */;



    // exemplar begin
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_15 initval 0x0000000000000000
    // exemplar attribute mem_0_14 initval 0x0000000000000000
    // exemplar attribute mem_0_13 initval 0x0000000000000000
    // exemplar attribute mem_0_12 initval 0x0000000000000000
    // exemplar attribute mem_0_11 initval 0x0000000000000000
    // exemplar attribute mem_0_10 initval 0x0000000000000000
    // exemplar attribute mem_0_9 initval 0x0000000000000000
    // exemplar attribute mem_0_8 initval 0x0000000000000000
    // exemplar attribute mem_0_7 initval 0x0000000000000000
    // exemplar attribute mem_0_6 initval 0x0000000000000000
    // exemplar attribute mem_0_5 initval 0xFFFFFFFFFFFC0000
    // exemplar attribute mem_0_4 initval 0xFFFFFFF00003FFE0
    // exemplar attribute mem_0_3 initval 0xFFFF800FF803FC18
    // exemplar attribute mem_0_2 initval 0xFFE07F0F87C3C396
    // exemplar attribute mem_0_1 initval 0xFE1C78CC6733324C
    // exemplar attribute mem_0_0 initval 0xF19B64AB56AAAB14
    // exemplar end

endmodule
