/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n pixel_fifo -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5a00 -type ebfifo -pfu_fifo -depth 2 -width 128 -depth 2 -rdata_width 128 -no_enable -pe -1 -pf -1  */
/* Mon Feb 14 20:46:56 2022 */


`timescale 1 ns / 1 ps
module pixel_fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [127:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [127:0] Q;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire w_gdata_0;
    wire wptr_1;
    wire r_gdata_0;
    wire rptr_1;
    wire w_gcount_0;
    wire w_gcount_1;
    wire r_gcount_0;
    wire r_gcount_1;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire empty_i;
    wire rRst;
    wire full_i;
    wire iwcount_0;
    wire iwcount_1;
    wire co0;
    wire w_gctr_ci;
    wire wcount_1;
    wire scuba_vhi;
    wire ircount_0;
    wire ircount_1;
    wire co0_1;
    wire r_gctr_ci;
    wire rcount_1;
    wire rden_i;
    wire cmp_ci;
    wire wcount_r0;
    wire empty_cmp_clr;
    wire rcount_0;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire wren_i;
    wire cmp_ci_1;
    wire rcount_w0;
    wire full_cmp_clr;
    wire wcount_0;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire rdataout127;
    wire rdataout126;
    wire rdataout125;
    wire rdataout124;
    wire rdataout123;
    wire rdataout122;
    wire rdataout121;
    wire rdataout120;
    wire rdataout119;
    wire rdataout118;
    wire rdataout117;
    wire rdataout116;
    wire rdataout115;
    wire rdataout114;
    wire rdataout113;
    wire rdataout112;
    wire rdataout111;
    wire rdataout110;
    wire rdataout109;
    wire rdataout108;
    wire rdataout107;
    wire rdataout106;
    wire rdataout105;
    wire rdataout104;
    wire rdataout103;
    wire rdataout102;
    wire rdataout101;
    wire rdataout100;
    wire rdataout99;
    wire rdataout98;
    wire rdataout97;
    wire rdataout96;
    wire rdataout95;
    wire rdataout94;
    wire rdataout93;
    wire rdataout92;
    wire rdataout91;
    wire rdataout90;
    wire rdataout89;
    wire rdataout88;
    wire rdataout87;
    wire rdataout86;
    wire rdataout85;
    wire rdataout84;
    wire rdataout83;
    wire rdataout82;
    wire rdataout81;
    wire rdataout80;
    wire rdataout79;
    wire rdataout78;
    wire rdataout77;
    wire rdataout76;
    wire rdataout75;
    wire rdataout74;
    wire rdataout73;
    wire rdataout72;
    wire rdataout71;
    wire rdataout70;
    wire rdataout69;
    wire rdataout68;
    wire rdataout67;
    wire rdataout66;
    wire rdataout65;
    wire rdataout64;
    wire rdataout63;
    wire rdataout62;
    wire rdataout61;
    wire rdataout60;
    wire rdataout59;
    wire rdataout58;
    wire rdataout57;
    wire rdataout56;
    wire rdataout55;
    wire rdataout54;
    wire rdataout53;
    wire rdataout52;
    wire rdataout51;
    wire rdataout50;
    wire rdataout49;
    wire rdataout48;
    wire rdataout47;
    wire rdataout46;
    wire rdataout45;
    wire rdataout44;
    wire rdataout43;
    wire rdataout42;
    wire rdataout41;
    wire rdataout40;
    wire rdataout39;
    wire rdataout38;
    wire rdataout37;
    wire rdataout36;
    wire rdataout35;
    wire rdataout34;
    wire rdataout33;
    wire rdataout32;
    wire rdataout31;
    wire rdataout30;
    wire rdataout29;
    wire rdataout28;
    wire rdataout27;
    wire rdataout26;
    wire rdataout25;
    wire rdataout24;
    wire rdataout23;
    wire rdataout22;
    wire rdataout21;
    wire rdataout20;
    wire rdataout19;
    wire rdataout18;
    wire rdataout17;
    wire rdataout16;
    wire rdataout15;
    wire rdataout14;
    wire rdataout13;
    wire rdataout12;
    wire rdataout11;
    wire rdataout10;
    wire rdataout9;
    wire rdataout8;
    wire rdataout7;
    wire rdataout6;
    wire rdataout5;
    wire rdataout4;
    wire rdataout3;
    wire rdataout2;
    wire rdataout1;
    wire rdataout0;
    wire rptr_0;
    wire dec0_wre3;
    wire scuba_vlo;
    wire wptr_0;

    AND2 AND2_t4 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t3 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t2 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t1 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t0 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    // synopsys translate_off
    defparam LUT4_6.initval =  16'h8000 ;
    // synopsys translate_on
    ROM16X1 LUT4_6 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(dec0_wre3))
             /* synthesis initval="0x8000" */;

    // synopsys translate_off
    defparam LUT4_5.initval =  16'h6996 ;
    // synopsys translate_on
    ROM16X1 LUT4_5 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r0))
             /* synthesis initval="0x6996" */;

    // synopsys translate_off
    defparam LUT4_4.initval =  16'h6996 ;
    // synopsys translate_on
    ROM16X1 LUT4_4 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w0))
             /* synthesis initval="0x6996" */;

    // synopsys translate_off
    defparam LUT4_3.initval =  16'h0410 ;
    // synopsys translate_on
    ROM16X1 LUT4_3 (.AD3(rptr_1), .AD2(rcount_1), .AD1(w_gcount_r21), .AD0(scuba_vlo), 
        .DO0(empty_cmp_set))
             /* synthesis initval="0x0410" */;

    // synopsys translate_off
    defparam LUT4_2.initval =  16'h1004 ;
    // synopsys translate_on
    ROM16X1 LUT4_2 (.AD3(rptr_1), .AD2(rcount_1), .AD1(w_gcount_r21), .AD0(scuba_vlo), 
        .DO0(empty_cmp_clr))
             /* synthesis initval="0x1004" */;

    // synopsys translate_off
    defparam LUT4_1.initval =  16'h0140 ;
    // synopsys translate_on
    ROM16X1 LUT4_1 (.AD3(wptr_1), .AD2(wcount_1), .AD1(r_gcount_w21), .AD0(scuba_vlo), 
        .DO0(full_cmp_set))
             /* synthesis initval="0x0140" */;

    // synopsys translate_off
    defparam LUT4_0.initval =  16'h4001 ;
    // synopsys translate_on
    ROM16X1 LUT4_0 (.AD3(wptr_1), .AD2(wcount_1), .AD1(r_gcount_w21), .AD0(scuba_vlo), 
        .DO0(full_cmp_clr))
             /* synthesis initval="0x4001" */;

    // synopsys translate_off
    defparam FF_149.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3BX FF_149 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_148.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_148 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_147.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_147 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_146.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_146 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_145.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_145 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_144.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_144 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_143.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3BX FF_143 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_142.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_142 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_141.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_141 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_140.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_140 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_139.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_139 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_138.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_138 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_137.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_137 (.D(rdataout0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_136.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_136 (.D(rdataout1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_135.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_135 (.D(rdataout2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_134.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_134 (.D(rdataout3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_133.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_133 (.D(rdataout4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_132.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_132 (.D(rdataout5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_131.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_131 (.D(rdataout6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_130.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_130 (.D(rdataout7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_129.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_129 (.D(rdataout8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_128.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_128 (.D(rdataout9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_127.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_127 (.D(rdataout10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_126.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_126 (.D(rdataout11), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_125.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_125 (.D(rdataout12), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_124.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_124 (.D(rdataout13), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_123.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_123 (.D(rdataout14), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_122.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_122 (.D(rdataout15), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_121.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_121 (.D(rdataout16), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_120.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_120 (.D(rdataout17), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_119.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_119 (.D(rdataout18), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[18]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_118.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_118 (.D(rdataout19), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[19]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_117.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_117 (.D(rdataout20), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[20]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_116.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_116 (.D(rdataout21), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[21]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_115.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_115 (.D(rdataout22), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[22]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_114.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_114 (.D(rdataout23), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[23]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_113.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_113 (.D(rdataout24), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[24]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_112.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_112 (.D(rdataout25), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[25]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_111.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_111 (.D(rdataout26), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[26]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_110.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_110 (.D(rdataout27), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[27]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_109.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_109 (.D(rdataout28), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[28]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_108.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_108 (.D(rdataout29), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[29]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_107.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_107 (.D(rdataout30), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[30]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_106.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_106 (.D(rdataout31), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[31]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_105.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_105 (.D(rdataout32), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[32]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_104.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_104 (.D(rdataout33), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[33]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_103.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_103 (.D(rdataout34), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[34]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_102.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_102 (.D(rdataout35), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[35]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_101.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_101 (.D(rdataout36), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[36]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_100.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_100 (.D(rdataout37), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[37]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_99.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_99 (.D(rdataout38), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[38]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_98.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_98 (.D(rdataout39), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[39]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_97.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_97 (.D(rdataout40), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[40]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_96.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_96 (.D(rdataout41), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[41]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_95.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_95 (.D(rdataout42), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[42]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_94.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_94 (.D(rdataout43), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[43]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_93.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_93 (.D(rdataout44), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[44]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_92.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_92 (.D(rdataout45), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[45]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_91.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_91 (.D(rdataout46), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[46]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_90.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_90 (.D(rdataout47), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[47]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_89.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_89 (.D(rdataout48), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[48]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_88.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_88 (.D(rdataout49), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[49]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_87.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_87 (.D(rdataout50), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[50]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_86.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_86 (.D(rdataout51), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[51]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_85.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_85 (.D(rdataout52), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[52]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_84.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_84 (.D(rdataout53), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[53]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_83.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_83 (.D(rdataout54), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[54]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_82.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_82 (.D(rdataout55), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[55]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_81.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_81 (.D(rdataout56), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[56]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_80.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_80 (.D(rdataout57), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[57]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_79.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_79 (.D(rdataout58), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[58]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_78.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_78 (.D(rdataout59), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[59]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_77.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_77 (.D(rdataout60), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[60]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_76.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_76 (.D(rdataout61), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[61]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_75.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_75 (.D(rdataout62), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[62]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_74.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_74 (.D(rdataout63), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[63]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_73.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_73 (.D(rdataout64), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[64]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_72.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_72 (.D(rdataout65), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[65]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_71.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_71 (.D(rdataout66), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[66]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_70.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_70 (.D(rdataout67), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[67]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_69.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_69 (.D(rdataout68), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[68]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_68.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_68 (.D(rdataout69), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[69]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_67.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_67 (.D(rdataout70), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[70]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_66.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_66 (.D(rdataout71), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[71]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_65.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_65 (.D(rdataout72), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[72]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_64.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_64 (.D(rdataout73), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[73]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_63.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_63 (.D(rdataout74), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[74]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_62.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_62 (.D(rdataout75), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[75]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_61.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_61 (.D(rdataout76), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[76]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_60.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_60 (.D(rdataout77), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[77]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_59.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_59 (.D(rdataout78), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[78]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_58.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_58 (.D(rdataout79), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[79]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_57.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_57 (.D(rdataout80), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[80]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_56.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_56 (.D(rdataout81), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[81]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_55.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_55 (.D(rdataout82), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[82]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_54.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_54 (.D(rdataout83), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[83]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_53.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_53 (.D(rdataout84), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[84]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_52.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_52 (.D(rdataout85), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[85]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_51.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_51 (.D(rdataout86), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[86]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_50.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_50 (.D(rdataout87), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[87]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_49.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_49 (.D(rdataout88), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[88]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_48.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_48 (.D(rdataout89), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[89]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_47.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_47 (.D(rdataout90), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[90]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_46.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_46 (.D(rdataout91), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[91]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_45.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_45 (.D(rdataout92), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[92]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_44.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_44 (.D(rdataout93), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[93]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_43.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_43 (.D(rdataout94), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[94]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_42.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_42 (.D(rdataout95), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[95]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_41.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_41 (.D(rdataout96), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[96]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_40.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_40 (.D(rdataout97), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[97]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_39.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_39 (.D(rdataout98), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[98]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_38.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_38 (.D(rdataout99), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[99]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_37.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_37 (.D(rdataout100), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[100]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_36.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_36 (.D(rdataout101), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[101]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_35.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_35 (.D(rdataout102), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[102]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_34.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_34 (.D(rdataout103), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[103]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_33.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_33 (.D(rdataout104), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[104]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_32.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_32 (.D(rdataout105), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[105]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_31.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_31 (.D(rdataout106), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[106]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_30.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_30 (.D(rdataout107), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[107]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_29.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_29 (.D(rdataout108), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[108]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_28.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_28 (.D(rdataout109), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[109]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_27.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_27 (.D(rdataout110), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[110]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_26.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_26 (.D(rdataout111), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[111]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_25.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_25 (.D(rdataout112), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[112]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_24.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_24 (.D(rdataout113), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[113]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_23.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_23 (.D(rdataout114), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[114]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_22.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_22 (.D(rdataout115), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[115]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_21.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_21 (.D(rdataout116), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[116]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_20.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_20 (.D(rdataout117), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[117]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_19.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_19 (.D(rdataout118), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[118]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_18.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_18 (.D(rdataout119), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[119]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_17.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_17 (.D(rdataout120), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[120]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_16.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_16 (.D(rdataout121), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[121]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_15 (.D(rdataout122), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[122]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(rdataout123), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[123]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(rdataout124), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[124]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(rdataout125), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[125]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(rdataout126), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[126]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(rdataout127), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[127]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_9 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_8 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_7 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_6 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_5 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_4 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_3 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_2 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3BX FF_1 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1S3DX FF_0 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FADD2B w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(w_gctr_ci), .S0(), .S1());

    CU2 w_gctr_0 (.CI(w_gctr_ci), .PC0(wcount_0), .PC1(wcount_1), .CO(co0), 
        .NC0(iwcount_0), .NC1(iwcount_1));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(r_gctr_ci), .S0(), .S1());

    CU2 r_gctr_0 (.CI(r_gctr_ci), .PC0(rcount_0), .PC1(rcount_1), .CO(co0_1), 
        .NC0(ircount_0), .NC1(ircount_1));

    FADD2B empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());

    AGEB2 empty_cmp_0 (.A0(rcount_0), .A1(empty_cmp_set), .B0(wcount_r0), 
        .B1(empty_cmp_clr), .CI(cmp_ci), .GE(empty_d_c));

    FADD2B a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(empty_d_c), .COUT(), .S0(empty_d), .S1());

    FADD2B full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .CI(scuba_vlo), .COUT(cmp_ci_1), .S0(), .S1());

    AGEB2 full_cmp_0 (.A0(wcount_0), .A1(full_cmp_set), .B0(rcount_w0), 
        .B1(full_cmp_clr), .CI(cmp_ci_1), .GE(full_d_c));

    FADD2B a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(full_d_c), .COUT(), .S0(full_d), .S1());

    DPR16X4A fifo_pfu_0_0 (.DI0(Data[124]), .DI1(Data[125]), .DI2(Data[126]), 
        .DI3(Data[127]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(scuba_vlo), .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), 
        .WAD1(scuba_vlo), .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout124), 
        .DO1(rdataout125), .DO2(rdataout126), .DO3(rdataout127));

    DPR16X4A fifo_pfu_0_1 (.DI0(Data[120]), .DI1(Data[121]), .DI2(Data[122]), 
        .DI3(Data[123]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(scuba_vlo), .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), 
        .WAD1(scuba_vlo), .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout120), 
        .DO1(rdataout121), .DO2(rdataout122), .DO3(rdataout123));

    DPR16X4A fifo_pfu_0_2 (.DI0(Data[116]), .DI1(Data[117]), .DI2(Data[118]), 
        .DI3(Data[119]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(scuba_vlo), .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), 
        .WAD1(scuba_vlo), .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout116), 
        .DO1(rdataout117), .DO2(rdataout118), .DO3(rdataout119));

    DPR16X4A fifo_pfu_0_3 (.DI0(Data[112]), .DI1(Data[113]), .DI2(Data[114]), 
        .DI3(Data[115]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(scuba_vlo), .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), 
        .WAD1(scuba_vlo), .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout112), 
        .DO1(rdataout113), .DO2(rdataout114), .DO3(rdataout115));

    DPR16X4A fifo_pfu_0_4 (.DI0(Data[108]), .DI1(Data[109]), .DI2(Data[110]), 
        .DI3(Data[111]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(scuba_vlo), .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), 
        .WAD1(scuba_vlo), .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout108), 
        .DO1(rdataout109), .DO2(rdataout110), .DO3(rdataout111));

    DPR16X4A fifo_pfu_0_5 (.DI0(Data[104]), .DI1(Data[105]), .DI2(Data[106]), 
        .DI3(Data[107]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(scuba_vlo), .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), 
        .WAD1(scuba_vlo), .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout104), 
        .DO1(rdataout105), .DO2(rdataout106), .DO3(rdataout107));

    DPR16X4A fifo_pfu_0_6 (.DI0(Data[100]), .DI1(Data[101]), .DI2(Data[102]), 
        .DI3(Data[103]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(scuba_vlo), .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), 
        .WAD1(scuba_vlo), .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout100), 
        .DO1(rdataout101), .DO2(rdataout102), .DO3(rdataout103));

    DPR16X4A fifo_pfu_0_7 (.DI0(Data[96]), .DI1(Data[97]), .DI2(Data[98]), 
        .DI3(Data[99]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout96), .DO1(rdataout97), 
        .DO2(rdataout98), .DO3(rdataout99));

    DPR16X4A fifo_pfu_0_8 (.DI0(Data[92]), .DI1(Data[93]), .DI2(Data[94]), 
        .DI3(Data[95]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout92), .DO1(rdataout93), 
        .DO2(rdataout94), .DO3(rdataout95));

    DPR16X4A fifo_pfu_0_9 (.DI0(Data[88]), .DI1(Data[89]), .DI2(Data[90]), 
        .DI3(Data[91]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout88), .DO1(rdataout89), 
        .DO2(rdataout90), .DO3(rdataout91));

    DPR16X4A fifo_pfu_0_10 (.DI0(Data[84]), .DI1(Data[85]), .DI2(Data[86]), 
        .DI3(Data[87]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout84), .DO1(rdataout85), 
        .DO2(rdataout86), .DO3(rdataout87));

    DPR16X4A fifo_pfu_0_11 (.DI0(Data[80]), .DI1(Data[81]), .DI2(Data[82]), 
        .DI3(Data[83]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout80), .DO1(rdataout81), 
        .DO2(rdataout82), .DO3(rdataout83));

    DPR16X4A fifo_pfu_0_12 (.DI0(Data[76]), .DI1(Data[77]), .DI2(Data[78]), 
        .DI3(Data[79]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout76), .DO1(rdataout77), 
        .DO2(rdataout78), .DO3(rdataout79));

    DPR16X4A fifo_pfu_0_13 (.DI0(Data[72]), .DI1(Data[73]), .DI2(Data[74]), 
        .DI3(Data[75]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout72), .DO1(rdataout73), 
        .DO2(rdataout74), .DO3(rdataout75));

    DPR16X4A fifo_pfu_0_14 (.DI0(Data[68]), .DI1(Data[69]), .DI2(Data[70]), 
        .DI3(Data[71]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout68), .DO1(rdataout69), 
        .DO2(rdataout70), .DO3(rdataout71));

    DPR16X4A fifo_pfu_0_15 (.DI0(Data[64]), .DI1(Data[65]), .DI2(Data[66]), 
        .DI3(Data[67]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout64), .DO1(rdataout65), 
        .DO2(rdataout66), .DO3(rdataout67));

    DPR16X4A fifo_pfu_0_16 (.DI0(Data[60]), .DI1(Data[61]), .DI2(Data[62]), 
        .DI3(Data[63]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout60), .DO1(rdataout61), 
        .DO2(rdataout62), .DO3(rdataout63));

    DPR16X4A fifo_pfu_0_17 (.DI0(Data[56]), .DI1(Data[57]), .DI2(Data[58]), 
        .DI3(Data[59]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout56), .DO1(rdataout57), 
        .DO2(rdataout58), .DO3(rdataout59));

    DPR16X4A fifo_pfu_0_18 (.DI0(Data[52]), .DI1(Data[53]), .DI2(Data[54]), 
        .DI3(Data[55]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout52), .DO1(rdataout53), 
        .DO2(rdataout54), .DO3(rdataout55));

    DPR16X4A fifo_pfu_0_19 (.DI0(Data[48]), .DI1(Data[49]), .DI2(Data[50]), 
        .DI3(Data[51]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout48), .DO1(rdataout49), 
        .DO2(rdataout50), .DO3(rdataout51));

    DPR16X4A fifo_pfu_0_20 (.DI0(Data[44]), .DI1(Data[45]), .DI2(Data[46]), 
        .DI3(Data[47]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout44), .DO1(rdataout45), 
        .DO2(rdataout46), .DO3(rdataout47));

    DPR16X4A fifo_pfu_0_21 (.DI0(Data[40]), .DI1(Data[41]), .DI2(Data[42]), 
        .DI3(Data[43]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout40), .DO1(rdataout41), 
        .DO2(rdataout42), .DO3(rdataout43));

    DPR16X4A fifo_pfu_0_22 (.DI0(Data[36]), .DI1(Data[37]), .DI2(Data[38]), 
        .DI3(Data[39]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout36), .DO1(rdataout37), 
        .DO2(rdataout38), .DO3(rdataout39));

    DPR16X4A fifo_pfu_0_23 (.DI0(Data[32]), .DI1(Data[33]), .DI2(Data[34]), 
        .DI3(Data[35]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout32), .DO1(rdataout33), 
        .DO2(rdataout34), .DO3(rdataout35));

    DPR16X4A fifo_pfu_0_24 (.DI0(Data[28]), .DI1(Data[29]), .DI2(Data[30]), 
        .DI3(Data[31]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout28), .DO1(rdataout29), 
        .DO2(rdataout30), .DO3(rdataout31));

    DPR16X4A fifo_pfu_0_25 (.DI0(Data[24]), .DI1(Data[25]), .DI2(Data[26]), 
        .DI3(Data[27]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout24), .DO1(rdataout25), 
        .DO2(rdataout26), .DO3(rdataout27));

    DPR16X4A fifo_pfu_0_26 (.DI0(Data[20]), .DI1(Data[21]), .DI2(Data[22]), 
        .DI3(Data[23]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout20), .DO1(rdataout21), 
        .DO2(rdataout22), .DO3(rdataout23));

    DPR16X4A fifo_pfu_0_27 (.DI0(Data[16]), .DI1(Data[17]), .DI2(Data[18]), 
        .DI3(Data[19]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout16), .DO1(rdataout17), 
        .DO2(rdataout18), .DO3(rdataout19));

    DPR16X4A fifo_pfu_0_28 (.DI0(Data[12]), .DI1(Data[13]), .DI2(Data[14]), 
        .DI3(Data[15]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout12), .DO1(rdataout13), 
        .DO2(rdataout14), .DO3(rdataout15));

    DPR16X4A fifo_pfu_0_29 (.DI0(Data[8]), .DI1(Data[9]), .DI2(Data[10]), 
        .DI3(Data[11]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout8), .DO1(rdataout9), 
        .DO2(rdataout10), .DO3(rdataout11));

    DPR16X4A fifo_pfu_0_30 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout4), .DO1(rdataout5), 
        .DO2(rdataout6), .DO3(rdataout7));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    DPR16X4A fifo_pfu_0_31 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(scuba_vlo), 
        .RAD2(scuba_vlo), .RAD3(scuba_vlo), .WAD0(wptr_0), .WAD1(scuba_vlo), 
        .WAD2(scuba_vlo), .WAD3(scuba_vlo), .DO0(rdataout0), .DO1(rdataout1), 
        .DO2(rdataout2), .DO3(rdataout3));

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute LUT4_6 initval 0x8000
    // exemplar attribute LUT4_5 initval 0x6996
    // exemplar attribute LUT4_4 initval 0x6996
    // exemplar attribute LUT4_3 initval 0x0410
    // exemplar attribute LUT4_2 initval 0x1004
    // exemplar attribute LUT4_1 initval 0x0140
    // exemplar attribute LUT4_0 initval 0x4001
    // exemplar attribute FF_149 GSR ENABLED
    // exemplar attribute FF_148 GSR ENABLED
    // exemplar attribute FF_147 GSR ENABLED
    // exemplar attribute FF_146 GSR ENABLED
    // exemplar attribute FF_145 GSR ENABLED
    // exemplar attribute FF_144 GSR ENABLED
    // exemplar attribute FF_143 GSR ENABLED
    // exemplar attribute FF_142 GSR ENABLED
    // exemplar attribute FF_141 GSR ENABLED
    // exemplar attribute FF_140 GSR ENABLED
    // exemplar attribute FF_139 GSR ENABLED
    // exemplar attribute FF_138 GSR ENABLED
    // exemplar attribute FF_137 GSR ENABLED
    // exemplar attribute FF_136 GSR ENABLED
    // exemplar attribute FF_135 GSR ENABLED
    // exemplar attribute FF_134 GSR ENABLED
    // exemplar attribute FF_133 GSR ENABLED
    // exemplar attribute FF_132 GSR ENABLED
    // exemplar attribute FF_131 GSR ENABLED
    // exemplar attribute FF_130 GSR ENABLED
    // exemplar attribute FF_129 GSR ENABLED
    // exemplar attribute FF_128 GSR ENABLED
    // exemplar attribute FF_127 GSR ENABLED
    // exemplar attribute FF_126 GSR ENABLED
    // exemplar attribute FF_125 GSR ENABLED
    // exemplar attribute FF_124 GSR ENABLED
    // exemplar attribute FF_123 GSR ENABLED
    // exemplar attribute FF_122 GSR ENABLED
    // exemplar attribute FF_121 GSR ENABLED
    // exemplar attribute FF_120 GSR ENABLED
    // exemplar attribute FF_119 GSR ENABLED
    // exemplar attribute FF_118 GSR ENABLED
    // exemplar attribute FF_117 GSR ENABLED
    // exemplar attribute FF_116 GSR ENABLED
    // exemplar attribute FF_115 GSR ENABLED
    // exemplar attribute FF_114 GSR ENABLED
    // exemplar attribute FF_113 GSR ENABLED
    // exemplar attribute FF_112 GSR ENABLED
    // exemplar attribute FF_111 GSR ENABLED
    // exemplar attribute FF_110 GSR ENABLED
    // exemplar attribute FF_109 GSR ENABLED
    // exemplar attribute FF_108 GSR ENABLED
    // exemplar attribute FF_107 GSR ENABLED
    // exemplar attribute FF_106 GSR ENABLED
    // exemplar attribute FF_105 GSR ENABLED
    // exemplar attribute FF_104 GSR ENABLED
    // exemplar attribute FF_103 GSR ENABLED
    // exemplar attribute FF_102 GSR ENABLED
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
