/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n pll_24M -lang verilog -synth synplify -arch ep5a00 -type pll -fin 100 -phase_cntl STATIC -fclkop 24 -fclkop_tol 0.0 -delay_cntl AUTO_NO_DELAY -fb_mode CLOCKTREE -extcap ENABLED -noclkos -noclkok -norst  */
/* Sun Sep 19 22:26:33 2021 */


`timescale 1 ns / 1 ps
module pll_24M (CLK, CLKOP, LOCK)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLK;
    output wire CLKOP;
    output wire LOCK;

    wire CLKOP_t;
    wire scuba_vlo;
    wire CLK_t;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam PLLDInst_0.PLLCAP = "ENABLED" ;
    defparam PLLDInst_0.CLKOK_BYPASS = "DISABLED" ;
    defparam PLLDInst_0.CLKOK_DIV = 2 ;
    defparam PLLDInst_0.CLKOS_BYPASS = "DISABLED" ;
    defparam PLLDInst_0.CLKOP_BYPASS = "DISABLED" ;
    defparam PLLDInst_0.PHASE_CNTL = "STATIC" ;
    defparam PLLDInst_0.DUTY = 8 ;
    defparam PLLDInst_0.PHASEADJ = "0.0" ;
    defparam PLLDInst_0.CLKOP_DIV = 48 ;
    defparam PLLDInst_0.CLKFB_DIV = 6 ;
    defparam PLLDInst_0.CLKI_DIV = 25 ;
    // synopsys translate_on
    EPLLD PLLDInst_0 (.CLKI(CLK_t), .CLKFB(CLKOP_t), .RST(scuba_vlo), .RSTK(scuba_vlo), 
        .DPAMODE(scuba_vlo), .DRPAI3(scuba_vlo), .DRPAI2(scuba_vlo), .DRPAI1(scuba_vlo), 
        .DRPAI0(scuba_vlo), .DFPAI3(scuba_vlo), .DFPAI2(scuba_vlo), .DFPAI1(scuba_vlo), 
        .DFPAI0(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(), .CLKOK(), .LOCK(LOCK), 
        .CLKINTFB())
             /* synthesis PLLCAP="ENABLED" */
             /* synthesis PLLTYPE="AUTO" */
             /* synthesis CLKOK_BYPASS="DISABLED" */
             /* synthesis CLKOK_DIV="2" */
             /* synthesis CLKOS_BYPASS="DISABLED" */
             /* synthesis FREQUENCY_PIN_CLKOP="24.000000" */
             /* synthesis CLKOP_BYPASS="DISABLED" */
             /* synthesis PHASE_CNTL="STATIC" */
             /* synthesis FDEL="0" */
             /* synthesis DUTY="8" */
             /* synthesis PHASEADJ="0.0" */
             /* synthesis FREQUENCY_PIN_CLKI="100.000000" */
             /* synthesis CLKOP_DIV="48" */
             /* synthesis CLKFB_DIV="6" */
             /* synthesis CLKI_DIV="25" */
             /* synthesis FIN="100.000000" */;

    assign CLKOP = CLKOP_t;
    assign CLK_t = CLK;


    // exemplar begin
    // exemplar attribute PLLDInst_0 PLLCAP ENABLED
    // exemplar attribute PLLDInst_0 PLLTYPE AUTO
    // exemplar attribute PLLDInst_0 CLKOK_BYPASS DISABLED
    // exemplar attribute PLLDInst_0 CLKOK_DIV 2
    // exemplar attribute PLLDInst_0 CLKOS_BYPASS DISABLED
    // exemplar attribute PLLDInst_0 FREQUENCY_PIN_CLKOP 24.000000
    // exemplar attribute PLLDInst_0 CLKOP_BYPASS DISABLED
    // exemplar attribute PLLDInst_0 PHASE_CNTL STATIC
    // exemplar attribute PLLDInst_0 FDEL 0
    // exemplar attribute PLLDInst_0 DUTY 8
    // exemplar attribute PLLDInst_0 PHASEADJ 0.0
    // exemplar attribute PLLDInst_0 FREQUENCY_PIN_CLKI 100.000000
    // exemplar attribute PLLDInst_0 CLKOP_DIV 48
    // exemplar attribute PLLDInst_0 CLKFB_DIV 6
    // exemplar attribute PLLDInst_0 CLKI_DIV 25
    // exemplar attribute PLLDInst_0 FIN 100.000000
    // exemplar end

endmodule
