/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 6.5 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n row_buffer -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5a00 -type bram -wp 10 -rp 0011 -rdata_width 16 -data_width 256 -num_rows 40 -resetmode SYNC -cascade 11  */
/* Thu Jan 20 18:21:33 2022 */


`timescale 1 ns / 1 ps
module row_buffer (WrAddress, RdAddress, Data, WE, RdClock, RdClockEn, 
    Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [5:0] WrAddress;
    input wire [9:0] RdAddress;
    input wire [255:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [15:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    // synopsys translate_off
    defparam row_buffer_0_0_7.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_0_7.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_0_7.GSR = "DISABLED" ;
    defparam row_buffer_0_0_7.RESETMODE = "SYNC" ;
    defparam row_buffer_0_0_7.REGMODE = "NOREG" ;
    defparam row_buffer_0_0_7.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_0_7.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_0_7 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[16]), 
        .DI3(Data[17]), .DI4(Data[32]), .DI5(Data[33]), .DI6(Data[48]), 
        .DI7(Data[49]), .DI8(scuba_vlo), .DI9(Data[64]), .DI10(Data[65]), 
        .DI11(Data[80]), .DI12(Data[81]), .DI13(Data[96]), .DI14(Data[97]), 
        .DI15(Data[112]), .DI16(Data[113]), .DI17(scuba_vlo), .DI18(Data[128]), 
        .DI19(Data[129]), .DI20(Data[144]), .DI21(Data[145]), .DI22(Data[160]), 
        .DI23(Data[161]), .DI24(Data[176]), .DI25(Data[177]), .DI26(scuba_vlo), 
        .DI27(Data[192]), .DI28(Data[193]), .DI29(Data[208]), .DI30(Data[209]), 
        .DI31(Data[224]), .DI32(Data[225]), .DI33(Data[240]), .DI34(Data[241]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[0]), .DO1(Q[1]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_1_6.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_1_6.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_1_6.GSR = "DISABLED" ;
    defparam row_buffer_0_1_6.RESETMODE = "SYNC" ;
    defparam row_buffer_0_1_6.REGMODE = "NOREG" ;
    defparam row_buffer_0_1_6.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_1_6.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_1_6 (.DI0(Data[2]), .DI1(Data[3]), .DI2(Data[18]), 
        .DI3(Data[19]), .DI4(Data[34]), .DI5(Data[35]), .DI6(Data[50]), 
        .DI7(Data[51]), .DI8(scuba_vlo), .DI9(Data[66]), .DI10(Data[67]), 
        .DI11(Data[82]), .DI12(Data[83]), .DI13(Data[98]), .DI14(Data[99]), 
        .DI15(Data[114]), .DI16(Data[115]), .DI17(scuba_vlo), .DI18(Data[130]), 
        .DI19(Data[131]), .DI20(Data[146]), .DI21(Data[147]), .DI22(Data[162]), 
        .DI23(Data[163]), .DI24(Data[178]), .DI25(Data[179]), .DI26(scuba_vlo), 
        .DI27(Data[194]), .DI28(Data[195]), .DI29(Data[210]), .DI30(Data[211]), 
        .DI31(Data[226]), .DI32(Data[227]), .DI33(Data[242]), .DI34(Data[243]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[2]), .DO1(Q[3]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_2_5.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_2_5.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_2_5.GSR = "DISABLED" ;
    defparam row_buffer_0_2_5.RESETMODE = "SYNC" ;
    defparam row_buffer_0_2_5.REGMODE = "NOREG" ;
    defparam row_buffer_0_2_5.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_2_5.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_2_5 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[20]), 
        .DI3(Data[21]), .DI4(Data[36]), .DI5(Data[37]), .DI6(Data[52]), 
        .DI7(Data[53]), .DI8(scuba_vlo), .DI9(Data[68]), .DI10(Data[69]), 
        .DI11(Data[84]), .DI12(Data[85]), .DI13(Data[100]), .DI14(Data[101]), 
        .DI15(Data[116]), .DI16(Data[117]), .DI17(scuba_vlo), .DI18(Data[132]), 
        .DI19(Data[133]), .DI20(Data[148]), .DI21(Data[149]), .DI22(Data[164]), 
        .DI23(Data[165]), .DI24(Data[180]), .DI25(Data[181]), .DI26(scuba_vlo), 
        .DI27(Data[196]), .DI28(Data[197]), .DI29(Data[212]), .DI30(Data[213]), 
        .DI31(Data[228]), .DI32(Data[229]), .DI33(Data[244]), .DI34(Data[245]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[4]), .DO1(Q[5]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_3_4.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_3_4.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_3_4.GSR = "DISABLED" ;
    defparam row_buffer_0_3_4.RESETMODE = "SYNC" ;
    defparam row_buffer_0_3_4.REGMODE = "NOREG" ;
    defparam row_buffer_0_3_4.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_3_4.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_3_4 (.DI0(Data[6]), .DI1(Data[7]), .DI2(Data[22]), 
        .DI3(Data[23]), .DI4(Data[38]), .DI5(Data[39]), .DI6(Data[54]), 
        .DI7(Data[55]), .DI8(scuba_vlo), .DI9(Data[70]), .DI10(Data[71]), 
        .DI11(Data[86]), .DI12(Data[87]), .DI13(Data[102]), .DI14(Data[103]), 
        .DI15(Data[118]), .DI16(Data[119]), .DI17(scuba_vlo), .DI18(Data[134]), 
        .DI19(Data[135]), .DI20(Data[150]), .DI21(Data[151]), .DI22(Data[166]), 
        .DI23(Data[167]), .DI24(Data[182]), .DI25(Data[183]), .DI26(scuba_vlo), 
        .DI27(Data[198]), .DI28(Data[199]), .DI29(Data[214]), .DI30(Data[215]), 
        .DI31(Data[230]), .DI32(Data[231]), .DI33(Data[246]), .DI34(Data[247]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[6]), .DO1(Q[7]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_4_3.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_4_3.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_4_3.GSR = "DISABLED" ;
    defparam row_buffer_0_4_3.RESETMODE = "SYNC" ;
    defparam row_buffer_0_4_3.REGMODE = "NOREG" ;
    defparam row_buffer_0_4_3.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_4_3.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_4_3 (.DI0(Data[8]), .DI1(Data[9]), .DI2(Data[24]), 
        .DI3(Data[25]), .DI4(Data[40]), .DI5(Data[41]), .DI6(Data[56]), 
        .DI7(Data[57]), .DI8(scuba_vlo), .DI9(Data[72]), .DI10(Data[73]), 
        .DI11(Data[88]), .DI12(Data[89]), .DI13(Data[104]), .DI14(Data[105]), 
        .DI15(Data[120]), .DI16(Data[121]), .DI17(scuba_vlo), .DI18(Data[136]), 
        .DI19(Data[137]), .DI20(Data[152]), .DI21(Data[153]), .DI22(Data[168]), 
        .DI23(Data[169]), .DI24(Data[184]), .DI25(Data[185]), .DI26(scuba_vlo), 
        .DI27(Data[200]), .DI28(Data[201]), .DI29(Data[216]), .DI30(Data[217]), 
        .DI31(Data[232]), .DI32(Data[233]), .DI33(Data[248]), .DI34(Data[249]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[8]), .DO1(Q[9]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_5_2.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_5_2.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_5_2.GSR = "DISABLED" ;
    defparam row_buffer_0_5_2.RESETMODE = "SYNC" ;
    defparam row_buffer_0_5_2.REGMODE = "NOREG" ;
    defparam row_buffer_0_5_2.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_5_2.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_5_2 (.DI0(Data[10]), .DI1(Data[11]), .DI2(Data[26]), 
        .DI3(Data[27]), .DI4(Data[42]), .DI5(Data[43]), .DI6(Data[58]), 
        .DI7(Data[59]), .DI8(scuba_vlo), .DI9(Data[74]), .DI10(Data[75]), 
        .DI11(Data[90]), .DI12(Data[91]), .DI13(Data[106]), .DI14(Data[107]), 
        .DI15(Data[122]), .DI16(Data[123]), .DI17(scuba_vlo), .DI18(Data[138]), 
        .DI19(Data[139]), .DI20(Data[154]), .DI21(Data[155]), .DI22(Data[170]), 
        .DI23(Data[171]), .DI24(Data[186]), .DI25(Data[187]), .DI26(scuba_vlo), 
        .DI27(Data[202]), .DI28(Data[203]), .DI29(Data[218]), .DI30(Data[219]), 
        .DI31(Data[234]), .DI32(Data[235]), .DI33(Data[250]), .DI34(Data[251]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[10]), .DO1(Q[11]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_6_1.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_6_1.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_6_1.GSR = "DISABLED" ;
    defparam row_buffer_0_6_1.RESETMODE = "SYNC" ;
    defparam row_buffer_0_6_1.REGMODE = "NOREG" ;
    defparam row_buffer_0_6_1.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_6_1.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_6_1 (.DI0(Data[12]), .DI1(Data[13]), .DI2(Data[28]), 
        .DI3(Data[29]), .DI4(Data[44]), .DI5(Data[45]), .DI6(Data[60]), 
        .DI7(Data[61]), .DI8(scuba_vlo), .DI9(Data[76]), .DI10(Data[77]), 
        .DI11(Data[92]), .DI12(Data[93]), .DI13(Data[108]), .DI14(Data[109]), 
        .DI15(Data[124]), .DI16(Data[125]), .DI17(scuba_vlo), .DI18(Data[140]), 
        .DI19(Data[141]), .DI20(Data[156]), .DI21(Data[157]), .DI22(Data[172]), 
        .DI23(Data[173]), .DI24(Data[188]), .DI25(Data[189]), .DI26(scuba_vlo), 
        .DI27(Data[204]), .DI28(Data[205]), .DI29(Data[220]), .DI30(Data[221]), 
        .DI31(Data[236]), .DI32(Data[237]), .DI33(Data[252]), .DI34(Data[253]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[12]), .DO1(Q[13]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam row_buffer_0_7_0.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_7_0.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_7_0.GSR = "DISABLED" ;
    defparam row_buffer_0_7_0.RESETMODE = "SYNC" ;
    defparam row_buffer_0_7_0.REGMODE = "NOREG" ;
    defparam row_buffer_0_7_0.DATA_WIDTH_R = 2 ;
    defparam row_buffer_0_7_0.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_7_0 (.DI0(Data[14]), .DI1(Data[15]), .DI2(Data[30]), 
        .DI3(Data[31]), .DI4(Data[46]), .DI5(Data[47]), .DI6(Data[62]), 
        .DI7(Data[63]), .DI8(scuba_vlo), .DI9(Data[78]), .DI10(Data[79]), 
        .DI11(Data[94]), .DI12(Data[95]), .DI13(Data[110]), .DI14(Data[111]), 
        .DI15(Data[126]), .DI16(Data[127]), .DI17(scuba_vlo), .DI18(Data[142]), 
        .DI19(Data[143]), .DI20(Data[158]), .DI21(Data[159]), .DI22(Data[174]), 
        .DI23(Data[175]), .DI24(Data[190]), .DI25(Data[191]), .DI26(scuba_vlo), 
        .DI27(Data[206]), .DI28(Data[207]), .DI29(Data[222]), .DI30(Data[223]), 
        .DI31(Data[238]), .DI32(Data[239]), .DI33(Data[254]), .DI34(Data[255]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(RdAddress[0]), .ADR2(RdAddress[1]), .ADR3(RdAddress[2]), .ADR4(RdAddress[3]), 
        .ADR5(RdAddress[4]), .ADR6(RdAddress[5]), .ADR7(RdAddress[6]), .ADR8(RdAddress[7]), 
        .ADR9(RdAddress[8]), .ADR10(RdAddress[9]), .ADR11(scuba_vlo), .ADR12(scuba_vlo), 
        .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[14]), .DO1(Q[15]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), 
        .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), 
        .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="2" */
             /* synthesis DATA_WIDTH_W="36" */;



    // exemplar begin
    // exemplar attribute row_buffer_0_0_7 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_0_7 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_0_7 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_0_7 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_0_7 GSR DISABLED
    // exemplar attribute row_buffer_0_0_7 RESETMODE SYNC
    // exemplar attribute row_buffer_0_0_7 REGMODE NOREG
    // exemplar attribute row_buffer_0_0_7 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_0_7 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_1_6 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_1_6 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_1_6 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_1_6 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_1_6 GSR DISABLED
    // exemplar attribute row_buffer_0_1_6 RESETMODE SYNC
    // exemplar attribute row_buffer_0_1_6 REGMODE NOREG
    // exemplar attribute row_buffer_0_1_6 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_1_6 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_2_5 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_2_5 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_2_5 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_2_5 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_2_5 GSR DISABLED
    // exemplar attribute row_buffer_0_2_5 RESETMODE SYNC
    // exemplar attribute row_buffer_0_2_5 REGMODE NOREG
    // exemplar attribute row_buffer_0_2_5 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_2_5 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_3_4 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_3_4 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_3_4 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_3_4 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_3_4 GSR DISABLED
    // exemplar attribute row_buffer_0_3_4 RESETMODE SYNC
    // exemplar attribute row_buffer_0_3_4 REGMODE NOREG
    // exemplar attribute row_buffer_0_3_4 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_3_4 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_4_3 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_4_3 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_4_3 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_4_3 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_4_3 GSR DISABLED
    // exemplar attribute row_buffer_0_4_3 RESETMODE SYNC
    // exemplar attribute row_buffer_0_4_3 REGMODE NOREG
    // exemplar attribute row_buffer_0_4_3 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_4_3 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_5_2 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_5_2 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_5_2 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_5_2 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_5_2 GSR DISABLED
    // exemplar attribute row_buffer_0_5_2 RESETMODE SYNC
    // exemplar attribute row_buffer_0_5_2 REGMODE NOREG
    // exemplar attribute row_buffer_0_5_2 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_5_2 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_6_1 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_6_1 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_6_1 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_6_1 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_6_1 GSR DISABLED
    // exemplar attribute row_buffer_0_6_1 RESETMODE SYNC
    // exemplar attribute row_buffer_0_6_1 REGMODE NOREG
    // exemplar attribute row_buffer_0_6_1 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_6_1 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_7_0 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_7_0 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_7_0 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_7_0 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_7_0 GSR DISABLED
    // exemplar attribute row_buffer_0_7_0 RESETMODE SYNC
    // exemplar attribute row_buffer_0_7_0 REGMODE NOREG
    // exemplar attribute row_buffer_0_7_0 DATA_WIDTH_R 2
    // exemplar attribute row_buffer_0_7_0 DATA_WIDTH_W 36
    // exemplar end

endmodule
