/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n ddr_mem -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5a00 -type iol -mode mem -width 1056 -freq 133 -sensitivity high -iobuf 252 -lsr reset -tristate dq -tristate dqs  */
/* Thu Sep 09 14:24:38 2021 */


`timescale 1 ns / 1 ps
module ddr_mem (dq, dqs, clk, reset, uddcntl, read, dataout_p, dataout_n, 
    datatri_p, datatri_n, dqstri_p, dqstri_n, ddrclk, datain_p, datain_n, 
    dqsc, prmbdet, lock, datavalid)/* synthesis NGD_DRC_MASK=1 */;
    input wire clk;
    input wire reset;
    input wire uddcntl;
    input wire [3:0] read;
    input wire [31:0] dataout_p;
    input wire [31:0] dataout_n;
    input wire [31:0] datatri_p;
    input wire [31:0] datatri_n;
    input wire [3:0] dqstri_p;
    input wire [3:0] dqstri_n;
    output wire [1:0] ddrclk;
    output wire [31:0] datain_p;
    output wire [31:0] datain_n;
    output wire [3:0] dqsc;
    output wire [3:0] prmbdet;
    output wire lock;
    output wire [3:0] datavalid;
    inout wire [31:0] dq;
    inout wire [3:0] dqs;

    wire ddrclk_t;
    wire scuba_vlo;
    wire scuba_vhi;
    wire dqsxfer_sig3;
    wire ddrclkpol_sig3;
    wire dqsbuf3;
    wire dqsxfer_sig2;
    wire ddrclkpol_sig2;
    wire dqsbuf2;
    wire dqsxfer_sig1;
    wire ddrclkpol_sig1;
    wire dqsbuf1;
    wire dqsxfer_sig0;
    wire ddrclkpol_sig0;
    wire dqsbuf0;
    wire dqsdel;
    wire dqsin3;
    wire dqstri3;
    wire dqsout3;
    wire dqsin2;
    wire dqstri2;
    wire dqsout2;
    wire dqsin1;
    wire dqstri1;
    wire dqsout1;
    wire dqsin0;
    wire dqstri0;
    wire dqsout0;
    wire ddrin31;
    wire datatri31;
    wire ddrout31;
    wire ddrin30;
    wire datatri30;
    wire ddrout30;
    wire ddrin29;
    wire datatri29;
    wire ddrout29;
    wire ddrin28;
    wire datatri28;
    wire ddrout28;
    wire ddrin27;
    wire datatri27;
    wire ddrout27;
    wire ddrin26;
    wire datatri26;
    wire ddrout26;
    wire ddrin25;
    wire datatri25;
    wire ddrout25;
    wire ddrin24;
    wire datatri24;
    wire ddrout24;
    wire ddrin23;
    wire datatri23;
    wire ddrout23;
    wire ddrin22;
    wire datatri22;
    wire ddrout22;
    wire ddrin21;
    wire datatri21;
    wire ddrout21;
    wire ddrin20;
    wire datatri20;
    wire ddrout20;
    wire ddrin19;
    wire datatri19;
    wire ddrout19;
    wire ddrin18;
    wire datatri18;
    wire ddrout18;
    wire ddrin17;
    wire datatri17;
    wire ddrout17;
    wire ddrin16;
    wire datatri16;
    wire ddrout16;
    wire ddrin15;
    wire datatri15;
    wire ddrout15;
    wire ddrin14;
    wire datatri14;
    wire ddrout14;
    wire ddrin13;
    wire datatri13;
    wire ddrout13;
    wire ddrin12;
    wire datatri12;
    wire ddrout12;
    wire ddrin11;
    wire datatri11;
    wire ddrout11;
    wire ddrin10;
    wire datatri10;
    wire ddrout10;
    wire ddrin9;
    wire datatri9;
    wire ddrout9;
    wire ddrin8;
    wire datatri8;
    wire ddrout8;
    wire ddrin7;
    wire datatri7;
    wire ddrout7;
    wire ddrin6;
    wire datatri6;
    wire ddrout6;
    wire ddrin5;
    wire datatri5;
    wire ddrout5;
    wire ddrin4;
    wire datatri4;
    wire ddrout4;
    wire ddrin3;
    wire datatri3;
    wire ddrout3;
    wire ddrin2;
    wire datatri2;
    wire ddrout2;
    wire ddrin1;
    wire datatri1;
    wire ddrout1;
    wire ddrin0;
    wire datatri0;
    wire ddrout0;

    OB Inst11_OB_1 (.I(ddrclk_t), .O(ddrclk[0]))
             /* synthesis IO_TYPE="SSTL25D_II" */;
	
	OB Inst11_OB_2 (.I(ddrclk_t), .O(ddrclk[1]))
             /* synthesis IO_TYPE="SSTL25D_II" */;

    ODDRXC Inst10_ODDRXC (.DA(scuba_vhi), .DB(scuba_vlo), .CLK(clk), .RST(scuba_vlo), 
        .Q(ddrclk_t));

    ODDRXC Inst9_ODDRXC3 (.DA(scuba_vhi), .DB(scuba_vlo), .CLK(clk), .RST(scuba_vlo), 
        .Q(dqsout3));

    ODDRXC Inst9_ODDRXC2 (.DA(scuba_vhi), .DB(scuba_vlo), .CLK(clk), .RST(scuba_vlo), 
        .Q(dqsout2));

    ODDRXC Inst9_ODDRXC1 (.DA(scuba_vhi), .DB(scuba_vlo), .CLK(clk), .RST(scuba_vlo), 
        .Q(dqsout1));

    ODDRXC Inst9_ODDRXC0 (.DA(scuba_vhi), .DB(scuba_vlo), .CLK(clk), .RST(scuba_vlo), 
        .Q(dqsout0));

    ODDRXC Inst8_ODDRXC3 (.DA(dqstri_p[3]), .DB(dqstri_n[3]), .CLK(clk), 
        .RST(scuba_vlo), .Q(dqstri3));

    ODDRXC Inst8_ODDRXC2 (.DA(dqstri_p[2]), .DB(dqstri_n[2]), .CLK(clk), 
        .RST(scuba_vlo), .Q(dqstri2));

    ODDRXC Inst8_ODDRXC1 (.DA(dqstri_p[1]), .DB(dqstri_n[1]), .CLK(clk), 
        .RST(scuba_vlo), .Q(dqstri1));

    ODDRXC Inst8_ODDRXC0 (.DA(dqstri_p[0]), .DB(dqstri_n[0]), .CLK(clk), 
        .RST(scuba_vlo), .Q(dqstri0));

    ODDRMXA Inst7_ODDRMXA31 (.DA(dataout_p[31]), .DB(dataout_n[31]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout31));

    ODDRMXA Inst7_ODDRMXA30 (.DA(dataout_p[30]), .DB(dataout_n[30]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout30));

    ODDRMXA Inst7_ODDRMXA29 (.DA(dataout_p[29]), .DB(dataout_n[29]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout29));

    ODDRMXA Inst7_ODDRMXA28 (.DA(dataout_p[28]), .DB(dataout_n[28]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout28));

    ODDRMXA Inst7_ODDRMXA27 (.DA(dataout_p[27]), .DB(dataout_n[27]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout27));

    ODDRMXA Inst7_ODDRMXA26 (.DA(dataout_p[26]), .DB(dataout_n[26]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout26));

    ODDRMXA Inst7_ODDRMXA25 (.DA(dataout_p[25]), .DB(dataout_n[25]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout25));

    ODDRMXA Inst7_ODDRMXA24 (.DA(dataout_p[24]), .DB(dataout_n[24]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(ddrout24));

    ODDRMXA Inst7_ODDRMXA23 (.DA(dataout_p[23]), .DB(dataout_n[23]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout23));

    ODDRMXA Inst7_ODDRMXA22 (.DA(dataout_p[22]), .DB(dataout_n[22]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout22));

    ODDRMXA Inst7_ODDRMXA21 (.DA(dataout_p[21]), .DB(dataout_n[21]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout21));

    ODDRMXA Inst7_ODDRMXA20 (.DA(dataout_p[20]), .DB(dataout_n[20]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout20));

    ODDRMXA Inst7_ODDRMXA19 (.DA(dataout_p[19]), .DB(dataout_n[19]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout19));

    ODDRMXA Inst7_ODDRMXA18 (.DA(dataout_p[18]), .DB(dataout_n[18]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout18));

    ODDRMXA Inst7_ODDRMXA17 (.DA(dataout_p[17]), .DB(dataout_n[17]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout17));

    ODDRMXA Inst7_ODDRMXA16 (.DA(dataout_p[16]), .DB(dataout_n[16]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(ddrout16));

    ODDRMXA Inst7_ODDRMXA15 (.DA(dataout_p[15]), .DB(dataout_n[15]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout15));

    ODDRMXA Inst7_ODDRMXA14 (.DA(dataout_p[14]), .DB(dataout_n[14]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout14));

    ODDRMXA Inst7_ODDRMXA13 (.DA(dataout_p[13]), .DB(dataout_n[13]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout13));

    ODDRMXA Inst7_ODDRMXA12 (.DA(dataout_p[12]), .DB(dataout_n[12]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout12));

    ODDRMXA Inst7_ODDRMXA11 (.DA(dataout_p[11]), .DB(dataout_n[11]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout11));

    ODDRMXA Inst7_ODDRMXA10 (.DA(dataout_p[10]), .DB(dataout_n[10]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout10));

    ODDRMXA Inst7_ODDRMXA9 (.DA(dataout_p[9]), .DB(dataout_n[9]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout9));

    ODDRMXA Inst7_ODDRMXA8 (.DA(dataout_p[8]), .DB(dataout_n[8]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(ddrout8));

    ODDRMXA Inst7_ODDRMXA7 (.DA(dataout_p[7]), .DB(dataout_n[7]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout7));

    ODDRMXA Inst7_ODDRMXA6 (.DA(dataout_p[6]), .DB(dataout_n[6]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout6));

    ODDRMXA Inst7_ODDRMXA5 (.DA(dataout_p[5]), .DB(dataout_n[5]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout5));

    ODDRMXA Inst7_ODDRMXA4 (.DA(dataout_p[4]), .DB(dataout_n[4]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout4));

    ODDRMXA Inst7_ODDRMXA3 (.DA(dataout_p[3]), .DB(dataout_n[3]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout3));

    ODDRMXA Inst7_ODDRMXA2 (.DA(dataout_p[2]), .DB(dataout_n[2]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout2));

    ODDRMXA Inst7_ODDRMXA1 (.DA(dataout_p[1]), .DB(dataout_n[1]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout1));

    ODDRMXA Inst7_ODDRMXA0 (.DA(dataout_p[0]), .DB(dataout_n[0]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(ddrout0));

    ODDRMXA Inst6_ODDRMXA31 (.DA(datatri_p[31]), .DB(datatri_n[31]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri31));

    ODDRMXA Inst6_ODDRMXA30 (.DA(datatri_p[30]), .DB(datatri_n[30]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri30));

    ODDRMXA Inst6_ODDRMXA29 (.DA(datatri_p[29]), .DB(datatri_n[29]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri29));

    ODDRMXA Inst6_ODDRMXA28 (.DA(datatri_p[28]), .DB(datatri_n[28]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri28));

    ODDRMXA Inst6_ODDRMXA27 (.DA(datatri_p[27]), .DB(datatri_n[27]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri27));

    ODDRMXA Inst6_ODDRMXA26 (.DA(datatri_p[26]), .DB(datatri_n[26]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri26));

    ODDRMXA Inst6_ODDRMXA25 (.DA(datatri_p[25]), .DB(datatri_n[25]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri25));

    ODDRMXA Inst6_ODDRMXA24 (.DA(datatri_p[24]), .DB(datatri_n[24]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig3), .RST(scuba_vlo), .Q(datatri24));

    ODDRMXA Inst6_ODDRMXA23 (.DA(datatri_p[23]), .DB(datatri_n[23]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri23));

    ODDRMXA Inst6_ODDRMXA22 (.DA(datatri_p[22]), .DB(datatri_n[22]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri22));

    ODDRMXA Inst6_ODDRMXA21 (.DA(datatri_p[21]), .DB(datatri_n[21]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri21));

    ODDRMXA Inst6_ODDRMXA20 (.DA(datatri_p[20]), .DB(datatri_n[20]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri20));

    ODDRMXA Inst6_ODDRMXA19 (.DA(datatri_p[19]), .DB(datatri_n[19]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri19));

    ODDRMXA Inst6_ODDRMXA18 (.DA(datatri_p[18]), .DB(datatri_n[18]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri18));

    ODDRMXA Inst6_ODDRMXA17 (.DA(datatri_p[17]), .DB(datatri_n[17]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri17));

    ODDRMXA Inst6_ODDRMXA16 (.DA(datatri_p[16]), .DB(datatri_n[16]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig2), .RST(scuba_vlo), .Q(datatri16));

    ODDRMXA Inst6_ODDRMXA15 (.DA(datatri_p[15]), .DB(datatri_n[15]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri15));

    ODDRMXA Inst6_ODDRMXA14 (.DA(datatri_p[14]), .DB(datatri_n[14]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri14));

    ODDRMXA Inst6_ODDRMXA13 (.DA(datatri_p[13]), .DB(datatri_n[13]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri13));

    ODDRMXA Inst6_ODDRMXA12 (.DA(datatri_p[12]), .DB(datatri_n[12]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri12));

    ODDRMXA Inst6_ODDRMXA11 (.DA(datatri_p[11]), .DB(datatri_n[11]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri11));

    ODDRMXA Inst6_ODDRMXA10 (.DA(datatri_p[10]), .DB(datatri_n[10]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri10));

    ODDRMXA Inst6_ODDRMXA9 (.DA(datatri_p[9]), .DB(datatri_n[9]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri9));

    ODDRMXA Inst6_ODDRMXA8 (.DA(datatri_p[8]), .DB(datatri_n[8]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig1), .RST(scuba_vlo), .Q(datatri8));

    ODDRMXA Inst6_ODDRMXA7 (.DA(datatri_p[7]), .DB(datatri_n[7]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri7));

    ODDRMXA Inst6_ODDRMXA6 (.DA(datatri_p[6]), .DB(datatri_n[6]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri6));

    ODDRMXA Inst6_ODDRMXA5 (.DA(datatri_p[5]), .DB(datatri_n[5]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri5));

    ODDRMXA Inst6_ODDRMXA4 (.DA(datatri_p[4]), .DB(datatri_n[4]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri4));

    ODDRMXA Inst6_ODDRMXA3 (.DA(datatri_p[3]), .DB(datatri_n[3]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri3));

    ODDRMXA Inst6_ODDRMXA2 (.DA(datatri_p[2]), .DB(datatri_n[2]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri2));

    ODDRMXA Inst6_ODDRMXA1 (.DA(datatri_p[1]), .DB(datatri_n[1]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri1));

    ODDRMXA Inst6_ODDRMXA0 (.DA(datatri_p[0]), .DB(datatri_n[0]), .CLK(clk), 
        .DQSXFER(dqsxfer_sig0), .RST(scuba_vlo), .Q(datatri0));

    IDDRMFX1A Inst5_IDDRMFX1A31 (.D(ddrin31), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[31]), .QB(datain_n[31]));

    IDDRMFX1A Inst5_IDDRMFX1A30 (.D(ddrin30), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[30]), .QB(datain_n[30]));

    IDDRMFX1A Inst5_IDDRMFX1A29 (.D(ddrin29), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[29]), .QB(datain_n[29]));

    IDDRMFX1A Inst5_IDDRMFX1A28 (.D(ddrin28), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[28]), .QB(datain_n[28]));

    IDDRMFX1A Inst5_IDDRMFX1A27 (.D(ddrin27), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[27]), .QB(datain_n[27]));

    IDDRMFX1A Inst5_IDDRMFX1A26 (.D(ddrin26), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[26]), .QB(datain_n[26]));

    IDDRMFX1A Inst5_IDDRMFX1A25 (.D(ddrin25), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[25]), .QB(datain_n[25]));

    IDDRMFX1A Inst5_IDDRMFX1A24 (.D(ddrin24), .ECLK(dqsbuf3), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig3), 
        .QA(datain_p[24]), .QB(datain_n[24]));

    IDDRMFX1A Inst5_IDDRMFX1A23 (.D(ddrin23), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[23]), .QB(datain_n[23]));

    IDDRMFX1A Inst5_IDDRMFX1A22 (.D(ddrin22), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[22]), .QB(datain_n[22]));

    IDDRMFX1A Inst5_IDDRMFX1A21 (.D(ddrin21), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[21]), .QB(datain_n[21]));

    IDDRMFX1A Inst5_IDDRMFX1A20 (.D(ddrin20), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[20]), .QB(datain_n[20]));

    IDDRMFX1A Inst5_IDDRMFX1A19 (.D(ddrin19), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[19]), .QB(datain_n[19]));

    IDDRMFX1A Inst5_IDDRMFX1A18 (.D(ddrin18), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[18]), .QB(datain_n[18]));

    IDDRMFX1A Inst5_IDDRMFX1A17 (.D(ddrin17), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[17]), .QB(datain_n[17]));

    IDDRMFX1A Inst5_IDDRMFX1A16 (.D(ddrin16), .ECLK(dqsbuf2), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig2), 
        .QA(datain_p[16]), .QB(datain_n[16]));

    IDDRMFX1A Inst5_IDDRMFX1A15 (.D(ddrin15), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[15]), .QB(datain_n[15]));

    IDDRMFX1A Inst5_IDDRMFX1A14 (.D(ddrin14), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[14]), .QB(datain_n[14]));

    IDDRMFX1A Inst5_IDDRMFX1A13 (.D(ddrin13), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[13]), .QB(datain_n[13]));

    IDDRMFX1A Inst5_IDDRMFX1A12 (.D(ddrin12), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[12]), .QB(datain_n[12]));

    IDDRMFX1A Inst5_IDDRMFX1A11 (.D(ddrin11), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[11]), .QB(datain_n[11]));

    IDDRMFX1A Inst5_IDDRMFX1A10 (.D(ddrin10), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[10]), .QB(datain_n[10]));

    IDDRMFX1A Inst5_IDDRMFX1A9 (.D(ddrin9), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[9]), .QB(datain_n[9]));

    IDDRMFX1A Inst5_IDDRMFX1A8 (.D(ddrin8), .ECLK(dqsbuf1), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig1), 
        .QA(datain_p[8]), .QB(datain_n[8]));

    IDDRMFX1A Inst5_IDDRMFX1A7 (.D(ddrin7), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[7]), .QB(datain_n[7]));

    IDDRMFX1A Inst5_IDDRMFX1A6 (.D(ddrin6), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[6]), .QB(datain_n[6]));

    IDDRMFX1A Inst5_IDDRMFX1A5 (.D(ddrin5), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[5]), .QB(datain_n[5]));

    IDDRMFX1A Inst5_IDDRMFX1A4 (.D(ddrin4), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[4]), .QB(datain_n[4]));

    IDDRMFX1A Inst5_IDDRMFX1A3 (.D(ddrin3), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[3]), .QB(datain_n[3]));

    IDDRMFX1A Inst5_IDDRMFX1A2 (.D(ddrin2), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[2]), .QB(datain_n[2]));

    IDDRMFX1A Inst5_IDDRMFX1A1 (.D(ddrin1), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[1]), .QB(datain_n[1]));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    IDDRMFX1A Inst5_IDDRMFX1A0 (.D(ddrin0), .ECLK(dqsbuf0), .CLK1(clk), 
        .CLK2(clk), .CE(scuba_vhi), .RST(scuba_vlo), .DDRCLKPOL(ddrclkpol_sig0), 
        .QA(datain_p[0]), .QB(datain_n[0]));

    // synopsys translate_off
    defparam Inst4_DQSDLL.LOCK_SENSITIVITY = "HIGH" ;
    // synopsys translate_on
    DQSDLL Inst4_DQSDLL (.CLK(clk), .RST(reset), .UDDCNTL(uddcntl), .LOCK(lock), 
        .DQSDEL(dqsdel))
             /* synthesis LOCK_SENSITIVITY="HIGH" */;

    // synopsys translate_off
    defparam Inst3_DQSBUFC3.DQS_LO_DEL_VAL = "0" ;
    defparam Inst3_DQSBUFC3.DQS_LO_DEL_ADJ = "PLUS" ;
    defparam Inst3_DQSBUFC3.DQS_LI_DEL_VAL = "4" ;
    defparam Inst3_DQSBUFC3.DQS_LI_DEL_ADJ = "MINUS" ;
    // synopsys translate_on
    DQSBUFC Inst3_DQSBUFC3 (.DQSI(dqsin3), .CLK(clk), .XCLK(clk), .READ(read[3]), 
        .DQSDEL(dqsdel), .DQSO(dqsbuf3), .DDRCLKPOL(ddrclkpol_sig3), .DQSC(dqsc[3]), 
        .PRMBDET(prmbdet[3]), .DQSXFER(dqsxfer_sig3), .DATAVALID(datavalid[3]))
             /* synthesis DQS_LO_DEL_VAL="0" */
             /* synthesis DQS_LO_DEL_ADJ="PLUS" */
             /* synthesis DQS_LI_DEL_VAL="4" */
             /* synthesis DQS_LI_DEL_ADJ="MINUS" */;

    // synopsys translate_off
    defparam Inst3_DQSBUFC2.DQS_LO_DEL_VAL = "0" ;
    defparam Inst3_DQSBUFC2.DQS_LO_DEL_ADJ = "PLUS" ;
    defparam Inst3_DQSBUFC2.DQS_LI_DEL_VAL = "4" ;
    defparam Inst3_DQSBUFC2.DQS_LI_DEL_ADJ = "MINUS" ;
    // synopsys translate_on
    DQSBUFC Inst3_DQSBUFC2 (.DQSI(dqsin2), .CLK(clk), .XCLK(clk), .READ(read[2]), 
        .DQSDEL(dqsdel), .DQSO(dqsbuf2), .DDRCLKPOL(ddrclkpol_sig2), .DQSC(dqsc[2]), 
        .PRMBDET(prmbdet[2]), .DQSXFER(dqsxfer_sig2), .DATAVALID(datavalid[2]))
             /* synthesis DQS_LO_DEL_VAL="0" */
             /* synthesis DQS_LO_DEL_ADJ="PLUS" */
             /* synthesis DQS_LI_DEL_VAL="4" */
             /* synthesis DQS_LI_DEL_ADJ="MINUS" */;

    // synopsys translate_off
    defparam Inst3_DQSBUFC1.DQS_LO_DEL_VAL = "0" ;
    defparam Inst3_DQSBUFC1.DQS_LO_DEL_ADJ = "PLUS" ;
    defparam Inst3_DQSBUFC1.DQS_LI_DEL_VAL = "4" ;
    defparam Inst3_DQSBUFC1.DQS_LI_DEL_ADJ = "MINUS" ;
    // synopsys translate_on
    DQSBUFC Inst3_DQSBUFC1 (.DQSI(dqsin1), .CLK(clk), .XCLK(clk), .READ(read[1]), 
        .DQSDEL(dqsdel), .DQSO(dqsbuf1), .DDRCLKPOL(ddrclkpol_sig1), .DQSC(dqsc[1]), 
        .PRMBDET(prmbdet[1]), .DQSXFER(dqsxfer_sig1), .DATAVALID(datavalid[1]))
             /* synthesis DQS_LO_DEL_VAL="0" */
             /* synthesis DQS_LO_DEL_ADJ="PLUS" */
             /* synthesis DQS_LI_DEL_VAL="4" */
             /* synthesis DQS_LI_DEL_ADJ="MINUS" */;

    // synopsys translate_off
    defparam Inst3_DQSBUFC0.DQS_LO_DEL_VAL = "0" ;
    defparam Inst3_DQSBUFC0.DQS_LO_DEL_ADJ = "PLUS" ;
    defparam Inst3_DQSBUFC0.DQS_LI_DEL_VAL = "4" ;
    defparam Inst3_DQSBUFC0.DQS_LI_DEL_ADJ = "MINUS" ;
    // synopsys translate_on
    DQSBUFC Inst3_DQSBUFC0 (.DQSI(dqsin0), .CLK(clk), .XCLK(clk), .READ(read[0]), 
        .DQSDEL(dqsdel), .DQSO(dqsbuf0), .DDRCLKPOL(ddrclkpol_sig0), .DQSC(dqsc[0]), 
        .PRMBDET(prmbdet[0]), .DQSXFER(dqsxfer_sig0), .DATAVALID(datavalid[0]))
             /* synthesis DQS_LO_DEL_VAL="0" */
             /* synthesis DQS_LO_DEL_ADJ="PLUS" */
             /* synthesis DQS_LI_DEL_VAL="4" */
             /* synthesis DQS_LI_DEL_ADJ="MINUS" */;

    BB Inst2_BB3 (.I(dqsout3), .T(dqstri3), .O(dqsin3), .B(dqs[3]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst2_BB2 (.I(dqsout2), .T(dqstri2), .O(dqsin2), .B(dqs[2]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst2_BB1 (.I(dqsout1), .T(dqstri1), .O(dqsin1), .B(dqs[1]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst2_BB0 (.I(dqsout0), .T(dqstri0), .O(dqsin0), .B(dqs[0]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB31 (.I(ddrout31), .T(datatri31), .O(ddrin31), .B(dq[31]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB30 (.I(ddrout30), .T(datatri30), .O(ddrin30), .B(dq[30]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB29 (.I(ddrout29), .T(datatri29), .O(ddrin29), .B(dq[29]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB28 (.I(ddrout28), .T(datatri28), .O(ddrin28), .B(dq[28]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB27 (.I(ddrout27), .T(datatri27), .O(ddrin27), .B(dq[27]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB26 (.I(ddrout26), .T(datatri26), .O(ddrin26), .B(dq[26]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB25 (.I(ddrout25), .T(datatri25), .O(ddrin25), .B(dq[25]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB24 (.I(ddrout24), .T(datatri24), .O(ddrin24), .B(dq[24]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB23 (.I(ddrout23), .T(datatri23), .O(ddrin23), .B(dq[23]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB22 (.I(ddrout22), .T(datatri22), .O(ddrin22), .B(dq[22]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB21 (.I(ddrout21), .T(datatri21), .O(ddrin21), .B(dq[21]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB20 (.I(ddrout20), .T(datatri20), .O(ddrin20), .B(dq[20]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB19 (.I(ddrout19), .T(datatri19), .O(ddrin19), .B(dq[19]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB18 (.I(ddrout18), .T(datatri18), .O(ddrin18), .B(dq[18]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB17 (.I(ddrout17), .T(datatri17), .O(ddrin17), .B(dq[17]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB16 (.I(ddrout16), .T(datatri16), .O(ddrin16), .B(dq[16]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB15 (.I(ddrout15), .T(datatri15), .O(ddrin15), .B(dq[15]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB14 (.I(ddrout14), .T(datatri14), .O(ddrin14), .B(dq[14]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB13 (.I(ddrout13), .T(datatri13), .O(ddrin13), .B(dq[13]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB12 (.I(ddrout12), .T(datatri12), .O(ddrin12), .B(dq[12]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB11 (.I(ddrout11), .T(datatri11), .O(ddrin11), .B(dq[11]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB10 (.I(ddrout10), .T(datatri10), .O(ddrin10), .B(dq[10]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB9 (.I(ddrout9), .T(datatri9), .O(ddrin9), .B(dq[9]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB8 (.I(ddrout8), .T(datatri8), .O(ddrin8), .B(dq[8]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB7 (.I(ddrout7), .T(datatri7), .O(ddrin7), .B(dq[7]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB6 (.I(ddrout6), .T(datatri6), .O(ddrin6), .B(dq[6]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB5 (.I(ddrout5), .T(datatri5), .O(ddrin5), .B(dq[5]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB4 (.I(ddrout4), .T(datatri4), .O(ddrin4), .B(dq[4]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB3 (.I(ddrout3), .T(datatri3), .O(ddrin3), .B(dq[3]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB2 (.I(ddrout2), .T(datatri2), .O(ddrin2), .B(dq[2]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB1 (.I(ddrout1), .T(datatri1), .O(ddrin1), .B(dq[1]))
             /* synthesis IO_TYPE="SSTL25_II" */;

    BB Inst1_BB0 (.I(ddrout0), .T(datatri0), .O(ddrin0), .B(dq[0]))
             /* synthesis IO_TYPE="SSTL25_II" */;



    // exemplar begin
    // exemplar attribute Inst11_OB IO_TYPE SSTL25D_II
    // exemplar attribute Inst4_DQSDLL LOCK_SENSITIVITY HIGH
    // exemplar attribute Inst3_DQSBUFC3 DQS_LO_DEL_VAL 0
    // exemplar attribute Inst3_DQSBUFC3 DQS_LO_DEL_ADJ PLUS
    // exemplar attribute Inst3_DQSBUFC3 DQS_LI_DEL_VAL 4
    // exemplar attribute Inst3_DQSBUFC3 DQS_LI_DEL_ADJ MINUS
    // exemplar attribute Inst3_DQSBUFC2 DQS_LO_DEL_VAL 0
    // exemplar attribute Inst3_DQSBUFC2 DQS_LO_DEL_ADJ PLUS
    // exemplar attribute Inst3_DQSBUFC2 DQS_LI_DEL_VAL 4
    // exemplar attribute Inst3_DQSBUFC2 DQS_LI_DEL_ADJ MINUS
    // exemplar attribute Inst3_DQSBUFC1 DQS_LO_DEL_VAL 0
    // exemplar attribute Inst3_DQSBUFC1 DQS_LO_DEL_ADJ PLUS
    // exemplar attribute Inst3_DQSBUFC1 DQS_LI_DEL_VAL 4
    // exemplar attribute Inst3_DQSBUFC1 DQS_LI_DEL_ADJ MINUS
    // exemplar attribute Inst3_DQSBUFC0 DQS_LO_DEL_VAL 0
    // exemplar attribute Inst3_DQSBUFC0 DQS_LO_DEL_ADJ PLUS
    // exemplar attribute Inst3_DQSBUFC0 DQS_LI_DEL_VAL 4
    // exemplar attribute Inst3_DQSBUFC0 DQS_LI_DEL_ADJ MINUS
    // exemplar attribute Inst2_BB3 IO_TYPE SSTL25_II
    // exemplar attribute Inst2_BB2 IO_TYPE SSTL25_II
    // exemplar attribute Inst2_BB1 IO_TYPE SSTL25_II
    // exemplar attribute Inst2_BB0 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB31 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB30 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB29 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB28 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB27 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB26 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB25 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB24 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB23 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB22 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB21 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB20 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB19 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB18 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB17 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB16 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB15 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB14 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB13 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB12 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB11 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB10 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB9 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB8 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB7 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB6 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB5 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB4 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB3 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB2 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB1 IO_TYPE SSTL25_II
    // exemplar attribute Inst1_BB0 IO_TYPE SSTL25_II
    // exemplar end

endmodule
