/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 6.5 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n row_buffer -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5a00 -type bram -wp 10 -rp 0011 -rdata_width 16 -data_width 128 -num_rows 80 -resetmode SYNC -cascade -1  */
/* Thu Sep 16 22:46:18 2021 */


`timescale 1 ns / 1 ps
module row_buffer (WrAddress, RdAddress, Data, WE, RdClock, RdClockEn, 
    Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [6:0] WrAddress;
    input wire [9:0] RdAddress;
    input wire [127:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [15:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    // synopsys translate_off
    defparam row_buffer_0_0_3.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_0_3.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_0_3.GSR = "DISABLED" ;
    defparam row_buffer_0_0_3.RESETMODE = "SYNC" ;
    defparam row_buffer_0_0_3.REGMODE = "NOREG" ;
    defparam row_buffer_0_0_3.DATA_WIDTH_R = 4 ;
    defparam row_buffer_0_0_3.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_0_3 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[16]), .DI5(Data[17]), .DI6(Data[18]), .DI7(Data[19]), 
        .DI8(scuba_vlo), .DI9(Data[32]), .DI10(Data[33]), .DI11(Data[34]), 
        .DI12(Data[35]), .DI13(Data[48]), .DI14(Data[49]), .DI15(Data[50]), 
        .DI16(Data[51]), .DI17(scuba_vlo), .DI18(Data[64]), .DI19(Data[65]), 
        .DI20(Data[66]), .DI21(Data[67]), .DI22(Data[80]), .DI23(Data[81]), 
        .DI24(Data[82]), .DI25(Data[83]), .DI26(scuba_vlo), .DI27(Data[96]), 
        .DI28(Data[97]), .DI29(Data[98]), .DI30(Data[99]), .DI31(Data[112]), 
        .DI32(Data[113]), .DI33(Data[114]), .DI34(Data[115]), .DI35(scuba_vlo), 
        .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), .ADW3(WrAddress[3]), 
        .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(WrAddress[6]), .ADW7(scuba_vlo), 
        .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), .BE2(scuba_vhi), 
        .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), .CSW0(WE), .CSW1(scuba_vlo), 
        .CSW2(scuba_vlo), .ADR0(scuba_vlo), .ADR1(scuba_vlo), .ADR2(RdAddress[0]), 
        .ADR3(RdAddress[1]), .ADR4(RdAddress[2]), .ADR5(RdAddress[3]), .ADR6(RdAddress[4]), 
        .ADR7(RdAddress[5]), .ADR8(RdAddress[6]), .ADR9(RdAddress[7]), .ADR10(RdAddress[8]), 
        .ADR11(RdAddress[9]), .ADR12(scuba_vlo), .ADR13(scuba_vlo), .CER(RdClockEn), 
        .CLKR(RdClock), .CSR0(scuba_vlo), .CSR1(scuba_vlo), .CSR2(scuba_vlo), 
        .RST(Reset), .DO0(Q[0]), .DO1(Q[1]), .DO2(Q[2]), .DO3(Q[3]), .DO4(), 
        .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), 
        .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .DO18(), .DO19(), .DO20(), 
        .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), .DO26(), .DO27(), .DO28(), 
        .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="4" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_1_2.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_1_2.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_1_2.GSR = "DISABLED" ;
    defparam row_buffer_0_1_2.RESETMODE = "SYNC" ;
    defparam row_buffer_0_1_2.REGMODE = "NOREG" ;
    defparam row_buffer_0_1_2.DATA_WIDTH_R = 4 ;
    defparam row_buffer_0_1_2.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_1_2 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .DI4(Data[20]), .DI5(Data[21]), .DI6(Data[22]), .DI7(Data[23]), 
        .DI8(scuba_vlo), .DI9(Data[36]), .DI10(Data[37]), .DI11(Data[38]), 
        .DI12(Data[39]), .DI13(Data[52]), .DI14(Data[53]), .DI15(Data[54]), 
        .DI16(Data[55]), .DI17(scuba_vlo), .DI18(Data[68]), .DI19(Data[69]), 
        .DI20(Data[70]), .DI21(Data[71]), .DI22(Data[84]), .DI23(Data[85]), 
        .DI24(Data[86]), .DI25(Data[87]), .DI26(scuba_vlo), .DI27(Data[100]), 
        .DI28(Data[101]), .DI29(Data[102]), .DI30(Data[103]), .DI31(Data[116]), 
        .DI32(Data[117]), .DI33(Data[118]), .DI34(Data[119]), .DI35(scuba_vlo), 
        .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), .ADW3(WrAddress[3]), 
        .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(WrAddress[6]), .ADW7(scuba_vlo), 
        .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), .BE2(scuba_vhi), 
        .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), .CSW0(WE), .CSW1(scuba_vlo), 
        .CSW2(scuba_vlo), .ADR0(scuba_vlo), .ADR1(scuba_vlo), .ADR2(RdAddress[0]), 
        .ADR3(RdAddress[1]), .ADR4(RdAddress[2]), .ADR5(RdAddress[3]), .ADR6(RdAddress[4]), 
        .ADR7(RdAddress[5]), .ADR8(RdAddress[6]), .ADR9(RdAddress[7]), .ADR10(RdAddress[8]), 
        .ADR11(RdAddress[9]), .ADR12(scuba_vlo), .ADR13(scuba_vlo), .CER(RdClockEn), 
        .CLKR(RdClock), .CSR0(scuba_vlo), .CSR1(scuba_vlo), .CSR2(scuba_vlo), 
        .RST(Reset), .DO0(Q[4]), .DO1(Q[5]), .DO2(Q[6]), .DO3(Q[7]), .DO4(), 
        .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), 
        .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .DO18(), .DO19(), .DO20(), 
        .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), .DO26(), .DO27(), .DO28(), 
        .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="4" */
             /* synthesis DATA_WIDTH_W="36" */;

    // synopsys translate_off
    defparam row_buffer_0_2_1.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_2_1.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_2_1.GSR = "DISABLED" ;
    defparam row_buffer_0_2_1.RESETMODE = "SYNC" ;
    defparam row_buffer_0_2_1.REGMODE = "NOREG" ;
    defparam row_buffer_0_2_1.DATA_WIDTH_R = 4 ;
    defparam row_buffer_0_2_1.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_2_1 (.DI0(Data[8]), .DI1(Data[9]), .DI2(Data[10]), 
        .DI3(Data[11]), .DI4(Data[24]), .DI5(Data[25]), .DI6(Data[26]), 
        .DI7(Data[27]), .DI8(scuba_vlo), .DI9(Data[40]), .DI10(Data[41]), 
        .DI11(Data[42]), .DI12(Data[43]), .DI13(Data[56]), .DI14(Data[57]), 
        .DI15(Data[58]), .DI16(Data[59]), .DI17(scuba_vlo), .DI18(Data[72]), 
        .DI19(Data[73]), .DI20(Data[74]), .DI21(Data[75]), .DI22(Data[88]), 
        .DI23(Data[89]), .DI24(Data[90]), .DI25(Data[91]), .DI26(scuba_vlo), 
        .DI27(Data[104]), .DI28(Data[105]), .DI29(Data[106]), .DI30(Data[107]), 
        .DI31(Data[120]), .DI32(Data[121]), .DI33(Data[122]), .DI34(Data[123]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(WrAddress[6]), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(RdAddress[0]), .ADR3(RdAddress[1]), .ADR4(RdAddress[2]), 
        .ADR5(RdAddress[3]), .ADR6(RdAddress[4]), .ADR7(RdAddress[5]), .ADR8(RdAddress[6]), 
        .ADR9(RdAddress[7]), .ADR10(RdAddress[8]), .ADR11(RdAddress[9]), 
        .ADR12(scuba_vlo), .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), 
        .CSR0(scuba_vlo), .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), 
        .DO0(Q[8]), .DO1(Q[9]), .DO2(Q[10]), .DO3(Q[11]), .DO4(), .DO5(), 
        .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), 
        .DO14(), .DO15(), .DO16(), .DO17(), .DO18(), .DO19(), .DO20(), .DO21(), 
        .DO22(), .DO23(), .DO24(), .DO25(), .DO26(), .DO27(), .DO28(), .DO29(), 
        .DO30(), .DO31(), .DO32(), .DO33(), .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="4" */
             /* synthesis DATA_WIDTH_W="36" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam row_buffer_0_3_0.CSDECODE_R =  3'b000 ;
    defparam row_buffer_0_3_0.CSDECODE_W =  3'b001 ;
    defparam row_buffer_0_3_0.GSR = "DISABLED" ;
    defparam row_buffer_0_3_0.RESETMODE = "SYNC" ;
    defparam row_buffer_0_3_0.REGMODE = "NOREG" ;
    defparam row_buffer_0_3_0.DATA_WIDTH_R = 4 ;
    defparam row_buffer_0_3_0.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB row_buffer_0_3_0 (.DI0(Data[12]), .DI1(Data[13]), .DI2(Data[14]), 
        .DI3(Data[15]), .DI4(Data[28]), .DI5(Data[29]), .DI6(Data[30]), 
        .DI7(Data[31]), .DI8(scuba_vlo), .DI9(Data[44]), .DI10(Data[45]), 
        .DI11(Data[46]), .DI12(Data[47]), .DI13(Data[60]), .DI14(Data[61]), 
        .DI15(Data[62]), .DI16(Data[63]), .DI17(scuba_vlo), .DI18(Data[76]), 
        .DI19(Data[77]), .DI20(Data[78]), .DI21(Data[79]), .DI22(Data[92]), 
        .DI23(Data[93]), .DI24(Data[94]), .DI25(Data[95]), .DI26(scuba_vlo), 
        .DI27(Data[108]), .DI28(Data[109]), .DI29(Data[110]), .DI30(Data[111]), 
        .DI31(Data[124]), .DI32(Data[125]), .DI33(Data[126]), .DI34(Data[127]), 
        .DI35(scuba_vlo), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), 
        .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(WrAddress[6]), 
        .ADW7(scuba_vlo), .ADW8(scuba_vlo), .BE0(scuba_vhi), .BE1(scuba_vhi), 
        .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(RdAddress[0]), .ADR3(RdAddress[1]), .ADR4(RdAddress[2]), 
        .ADR5(RdAddress[3]), .ADR6(RdAddress[4]), .ADR7(RdAddress[5]), .ADR8(RdAddress[6]), 
        .ADR9(RdAddress[7]), .ADR10(RdAddress[8]), .ADR11(RdAddress[9]), 
        .ADR12(scuba_vlo), .ADR13(scuba_vlo), .CER(RdClockEn), .CLKR(RdClock), 
        .CSR0(scuba_vlo), .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), 
        .DO0(Q[12]), .DO1(Q[13]), .DO2(Q[14]), .DO3(Q[15]), .DO4(), .DO5(), 
        .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), 
        .DO14(), .DO15(), .DO16(), .DO17(), .DO18(), .DO19(), .DO20(), .DO21(), 
        .DO22(), .DO23(), .DO24(), .DO25(), .DO26(), .DO27(), .DO28(), .DO29(), 
        .DO30(), .DO31(), .DO32(), .DO33(), .DO34(), .DO35())
             /* synthesis MEM_LPC_FILE="row_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis DATA_WIDTH_R="4" */
             /* synthesis DATA_WIDTH_W="36" */;



    // exemplar begin
    // exemplar attribute row_buffer_0_0_3 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_0_3 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_0_3 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_0_3 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_0_3 GSR DISABLED
    // exemplar attribute row_buffer_0_0_3 RESETMODE SYNC
    // exemplar attribute row_buffer_0_0_3 REGMODE NOREG
    // exemplar attribute row_buffer_0_0_3 DATA_WIDTH_R 4
    // exemplar attribute row_buffer_0_0_3 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_1_2 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_1_2 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_1_2 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_1_2 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_1_2 GSR DISABLED
    // exemplar attribute row_buffer_0_1_2 RESETMODE SYNC
    // exemplar attribute row_buffer_0_1_2 REGMODE NOREG
    // exemplar attribute row_buffer_0_1_2 DATA_WIDTH_R 4
    // exemplar attribute row_buffer_0_1_2 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_2_1 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_2_1 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_2_1 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_2_1 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_2_1 GSR DISABLED
    // exemplar attribute row_buffer_0_2_1 RESETMODE SYNC
    // exemplar attribute row_buffer_0_2_1 REGMODE NOREG
    // exemplar attribute row_buffer_0_2_1 DATA_WIDTH_R 4
    // exemplar attribute row_buffer_0_2_1 DATA_WIDTH_W 36
    // exemplar attribute row_buffer_0_3_0 MEM_LPC_FILE row_buffer.lpc
    // exemplar attribute row_buffer_0_3_0 MEM_INIT_FILE 
    // exemplar attribute row_buffer_0_3_0 CSDECODE_R 0b000
    // exemplar attribute row_buffer_0_3_0 CSDECODE_W 0b001
    // exemplar attribute row_buffer_0_3_0 GSR DISABLED
    // exemplar attribute row_buffer_0_3_0 RESETMODE SYNC
    // exemplar attribute row_buffer_0_3_0 REGMODE NOREG
    // exemplar attribute row_buffer_0_3_0 DATA_WIDTH_R 4
    // exemplar attribute row_buffer_0_3_0 DATA_WIDTH_W 36
    // exemplar end

endmodule
